### ISSUE TITLE
Error: Call to a member function select() on bool

### ISSUE THREAD

**Issue by Krapulat** [bentideswell/magento2-wordpress-integration#100]
I have multiple stores, but the WordPress is only activated in two of them.

In the other stores, where the module is not activated, I get this error in every category:

Error: Call to a member function select() on bool in magento2/vendor/fishpig/magento2-wordpress-integration/Model/OptionManager.php:54

**Comment by bentideswell** [comment]
Can you tell me what version you are using? Also, are you using any FishPig add-on modules and if so, what versions?

**Comment by bentideswell** [comment]
I have just released an update that should fix this issue.

**Comment by Krapulat** [comment]
@bentideswell Yes, now the issue is resolved. Thanks!

**Comment by Krapulat** [comment]
Following the environment: multiple store views and some of them the module is deactivated. I get the following error in the store views where the module is deactivated: main.CRITICAL: WordPress doesn't appear to be installed. at vendor/fishpig/magento2-wordpress-integration/Model/WPConfig.php:50
