### ISSUE TITLE
WordPress doesn't appear to be installed.

### ISSUE THREAD

**Issue by Krapulat** [bentideswell/magento2-wordpress-integration#101]
Multiple store views where in some of them the module is deactivated. I get the following error in the store views where the module is deactivated: main.CRITICAL: WordPress doesn't appear to be installed. at vendor/fishpig/magento2-wordpress-integration/Model/WPConfig.php:50

**Comment by bentideswell** [comment]
I cannot replicate this. If you can email SSH access details to me at help@fishpig.co.uk and provide steps for me to recreate the issue on your site, I will happily debug and fix the issue for you.

**Comment by bentideswell** [comment]
This has been resolved by a patch on [FishPig_WordPress_Yoast](https://github.com/bentideswell/magento2-wordpress-integration-yoastseo). Upgrading this module to the latest version has now resolved the issue.
