### ISSUE TITLE
Not working with Multi server deployment 

### ISSUE THREAD

**Issue by thai2301** [bentideswell/magento2-wordpress-integration#103]
https://github.com/bentideswell/magento2-wordpress-integration/blob/92452d178209e5cec02443f50458b1dc972bbaa2/Model/Theme.php#L99:L109

Not working with Multi server deployment when we need to share wp-content folder across all the webnodes. So now the is_dir returns false because it's a symlink.

**Comment by bentideswell** [comment]
Does it work if you change it to is_link?

**Comment by thai2301** [comment]
@bentideswell not test yet. Currently, I remove the is_dir validation because I can make sure they are exsting. And everything is working with the symlink.
So I think I will wait the official update for this.
