### ISSUE TITLE
No update available

### ISSUE THREAD

**Issue by EspertoMagento** [bentideswell/magento2-wordpress-integration#104]
Hello,
I have 2.0.11.42 version installed with composer.
I can't update the module to 2.0.14.4 with composer. Why?

I use this code:
`composer update fishpig/magento2-wordpress-integration`

Any help is appreciated.

**Comment by bentideswell** [comment]
There could be many reasons. What error message do you get?

My guess would be that you have a specific version in your composer.json file. You can change this to * and then re-run the command and it should update.

You could also try just running:

composer update fishpig/magento2-wordpress-integration:*

**Comment by EspertoMagento** [comment]
No errors. Only this:
```
Updating dependencies (including require-dev)
Nothing to install or update
```

also with:
`composer update fishpig/magento2-wordpress-integration:*`

I try to change composer.json manually.

**Comment by bentideswell** [comment]
You can see the latest version is available on packagist:

https://packagist.org/packages/fishpig/magento2-wordpress-integration

Manually set the version in composer.json to * and then re-run the command. You could also try running:

composer clear-cache

**Comment by EspertoMagento** [comment]
Ok manually it works, but is a strange behavior, don't you?

**Comment by bentideswell** [comment]
It is not behaviour that I have control over and is dictated by Composer and Packagist.

If you have a specific version set in composer.json then this version will stay, even if you run update. This allows you to control the version of certain packages and stop them from being upgraded unless you specifically want them upgraded.

**Comment by EspertoMagento** [comment]
Ok, thank you very much for your explanation!

**Comment by bentideswell** [comment]
No worries!
