### ISSUE TITLE
jQuery 3.5.1 loaded breaking the gallery on product pages

### ISSUE THREAD

**Issue by clivewalkden** [bentideswell/magento2-wordpress-integration#105]
Evening Ben,

We've noticed an issue with the latest WordPress 5.6.0 and it's updated version of jQuery.

Your AssetInjector is adding the following:
```
var RequireFPJS=requirejs.config({
  "baseUrl": require.toUrl(''),
  "context": "RequireFPJS",
  "paths": {
      "25517cca92f9d9863b21c92db674260c": "https://www.attwoolls.co.uk/static/version1611246328/frontend/FishPig/WordPress/js/25517cca92f9d9863b21c92db674260c"
  }
});
```

This is occasionally loading jQuery 3.5.1 on product pages causing the fotorama gallery to fail. The problem seems intermittent due to the RequireJS nature of the scripts load order. Any suggestions on a fix?

Kind regards,

Clive

**Comment by bentideswell** [comment]
I'm trying to recreate this on my dev environment but I haven't been able to.

The AssetInjector should forcefully remove jQuery from the WordPress includes so if it's not, it could be that a plugin is including it's own version of jQuery.

Can you try the following and report back please?

- Upgrade all FishPig modules
- Disable all WP plugins

At this point test again and see what happens. If the error is resolved, try enabling plugins one by one until you find the culprit and report back.

The JS files should be loaded in the same order every time, unless they are being included in a different order in WordPress.

Thanks!

**Comment by clivewalkden** [comment]
Ben,

I've not had time to try this again but will as soon as I can.

**Comment by bentideswell** [comment]
Hi Clive,

I've played around with this and finally managed to recreate the issue. I think WordPress had changed the filename from jquery.js to jquery.min.js so it evaded my code that tried to remove it.

I've just released an update that adresses this and the issue should now be resolved. I will close this issue but if the update doesn't resolve it for you, feel free to re-open it.
