### ISSUE TITLE
Share one blog across multiple sites

### ISSUE THREAD

**Issue by MichaelThessel** [bentideswell/magento2-wordpress-integration#106]
Hi,

We just ported from M1 to M2 and in our M1 install we were able to use the same WP install across multiple stores. I.e.

www.store1.com/blog
www.store2.com/blog

Both would show the same posts. We would like to re-create this on M2. Unfortunately we run into the home URL issue reported in #78.

In that issue you mentioned that you are working in that feature. Is there any chance that this will be supported in the near future?

**Comment by bentideswell** [comment]
Hi Michael,

This modification was added to the M2 module to prevent duplicate content. In your above situation, both URLs would share the same content so would have duplicate content issues. This caused issues for a lot of people so the change was made.

You now have to have a unique blog per URL (not per store). If your stores have the same URL then they can share the same blog (as this wouldn't cause duplicate content issues).

If you really want this change, you could write a module with a few plugins to disable the home URL check and then you would need to correctly canonicalise or use hreflang tags to resolve the duplicate content issues.
