### ISSUE TITLE
Issue with module.xml setup_version

### ISSUE THREAD

**Issue by jevgenijmokrousov** [bentideswell/magento2-wordpress-integration#107]
Hi there,
I'm pretty sure latest version was created based on Magento guidelines in regards to 2.4 version https://devdocs.magento.com/guides/v2.4/extension-dev-guide/build/create_component.html#add-component-xml which say - `Omit the setup_version parameter if you use Declarative Schema.`  unfortunately this will break any Magento 2.3.* version and simple not allow to run setup:upgrade https://ibb.co/2sqbMsr

**Comment by bentideswell** [comment]
I can add the version back in to module.xml but not keep incrementing it as each new version is released. This should stop forcing customers to run setup:upgrade after each upgrade but also allow it to work for Magento 2.3.*. Would this work for you?

**Comment by jevgenijmokrousov** [comment]
I would do the job for sure, nice one @bentideswell

**Comment by bentideswell** [comment]
I've just added this back in and released a new version. Thanks for the tip!
