### ISSUE TITLE
composer.json

### ISSUE THREAD

**Issue by jevgenijmokrousov** [bentideswell/magento2-wordpress-integration#108]
Would be good to add in to `require` things like:
"magento/module-sitemap": "100.3.*"
"magento/product-community-edition": "2.3.*"
as module latest releases wouldn't work properly on Magento 2.2.*

**Comment by bentideswell** [comment]
I will add back in setup_version and then this should allow the module to work on 2.2. Also the Sitemap module isn't a requirement as integrating with it is a required feature. If a user disables this module, FishPig_WordPress will still function.

**Comment by jevgenijmokrousov** [comment]
Hi @bentideswell , nice one appreciate it. Thing with Sitemap is that your latest version use `Magento\Sitemap\Model\ItemProvider\ItemProviderInterface` which is available since 100.3 only

**Comment by jevgenijmokrousov** [comment]
![image](https://user-images.githubusercontent.com/1798642/118238166-0d845a00-b490-11eb-99cc-bfa3a75f6f16.png)
![image](https://user-images.githubusercontent.com/1798642/118238185-170dc200-b490-11eb-955d-fa6c6c17ed6e.png)
![image](https://user-images.githubusercontent.com/1798642/118238249-2db41900-b490-11eb-9891-c926829d7c65.png)

Evidence provided ^

**Comment by bentideswell** [comment]
Yes you're right. Would the following work:

           "magento/module-sitemap": "^100.3"

This should accept any version from 100.3.
