### ISSUE TITLE
$post->isSticky() is always null

### ISSUE THREAD

**Issue by scunnercampbell** [bentideswell/magento2-wordpress-integration#110]
Hi, 
Flagging this as a potential issue on Wordpress 5.7.2, Magento 2.3.5, Fishpig 2.0.18.0 - the $post->isSticky() check in `FishPig_WordPress::post/list.phtml` is always null for me, even though the sticky post is correctly added to the top of the collection. The `$this->_getData('is_sticky')` in Model/Post.php doesn't appear to be being set as expected. 

Thanks

**Comment by bentideswell** [comment]
Hi @scunnercampbell, have you tried adding the [addStickyPostsToCollection](https://github.com/bentideswell/magento2-wordpress-integration/blob/master/Model/ResourceModel/Post/Collection.php#L214,L235) method to the collection?

**Comment by scunnercampbell** [comment]
Hey @bentideswell - thanks for the quick response. Ah, apologies, I see that needs to be called manually for regular listings, and that it's the homepage list block which uses the same template but adds the sticky post to the collection, unlike the regular listings.
