### ISSUE TITLE
Sidebar left or right nav bar with Fishpig it is blank.

### ISSUE THREAD

**Issue by willgoulding** [bentideswell/magento2-wordpress-integration#112]
Hello,

I need help.

Sidebar is not loading on the side column.

Magento versão 2.3.5-p1
WordPress Integration - 2.0.20.15

https://www.pood.com.br/blog

![image](https://user-images.githubusercontent.com/12437790/125676782-6e16a8c2-2297-42a8-b43e-3940b9ebe2b0.png)

Can anyone help me with this?

**Comment by bentideswell** [comment]
This usually is caused by some broken html in one of your posts that breaks the wrapping divs.
