### ISSUE TITLE
Magento 2.3.7-p3 incompatible with v3.9.2 ? Monolog\Logger::addRecord declaration incompatible?

### ISSUE THREAD

**Issue by sweetappleuk** [bentideswell/magento2-wordpress-integration#115]
After updating the Magento metapackage to v2.3.7-p3 bin/magento setup:upgrade fails with the following error

Warning: Declaration of FishPig\WordPress\App\Logger::addRecord(int $level, string $message, array $context = Array): bool should be compatible with Monolog\Logger::addRecord($level, $message, array $context = Array) in vendor/fishpig/magento2-wordpress-integration/App/Logger.php on line 46

Monolog in M2.3.7-p3 seems to be locked to the v1.x Monolog branch. This doesn't use int and string type hints in the addRecord() method signature.

Appears that the changes in v3.9.2  to make it compatible with M2.4.4 break compatibility with M2.3.x ?

**Comment by bentideswell** [comment]
Thanks for this. I have released version 3.9.3 and this fixes the issue for all versions of Magento. It does this by removing the addRecord method (which was causing the issue) and adds the functionality previously in this method into a Processor object.
