### ISSUE TITLE
Issue in parameters.

### ISSUE THREAD

**Issue by dev-ajaysaini** [bentideswell/magento2-wordpress-integration#119]
Getting issues in the latest version 3.24.5

**Steps to reproduce:**
1. Upgraded the module to latest version 3.24.5
2. Try to reload frontend after setup:upgrade

**Issues found:**
1. FishPig\WordPress\Model\IntegrationManager in this class constructor there is only one parameter which accept only **integrationTests** parameter of type **FishPig\WordPress\App\Integration\Tests**

`public function __construct(\FishPig\WordPress\App\Integration\Tests $integrationTests){
        $this->integrationTests = $integrationTests;
    }`
    
    
But parameter passed as an array in **fishpig/magento2-wordpress-integration-root** modules di.xml file.

`<type name="FishPig\WordPress\Model\IntegrationManager">
                <arguments>
			<argument name="integrationTests" xsi:type="array">
				<item name="path" xsi:type="object">FishPig\WordPress_Root\Model\Integration\CookiePathTest</item>
			</argument>
		</arguments>
	</type>`

**Actual Result:**
1 exception(s):
Exception #0 (UnexpectedValueException): Invalid parameter configuration provided for $integrationTests argument of FishPig\WordPress\Model\IntegrationManager

**Comment by bentideswell** [comment]
Hi @dev-ajaysaini, I think you may be using an old version of Root with the latest version of WordPress Integration as the di.xml you posted is old. You should always use the latest versions together. The latest version of the Root di.xml is:
````
<type name="FishPig\WordPress\App\Integration\Tests">
    <arguments>
        <argument name="integrationTestPool" xsi:type="array">
            <item name="rootCookiePathTest" xsi:type="object">FishPig\WordPress_Root\App\Integration\Tests\CookiePathTest</item>
        </argument>
    </arguments>
</type>
````

The class is no longer \FishPig\WordPress\Model\IntegrationManager as this has been deprecated and replaced with \FishPig\WordPress\App\Integration\Tests

Updating all FishPig modules to the latest version will resolve this issue.
