### ISSUE TITLE
Latest version v3.28.0 doesn't work below Magento 2.4.6

### ISSUE THREAD

**Issue by clivewalkden** [bentideswell/magento2-wordpress-integration#123]
Hi Ben,

Noted that the latest version of the module has updates to the Theme generation command which breaks on Magento below 2.4.6 due to its requirement of Symfony Console 5.x and older versions using the 4.4.x branch.

Thanks in advance.

Clive

**Comment by bentideswell** [comment]
Hi Clive,

Thanks for this. I've released an update which just returns an int, rather than the constants, which may or may not be defined, depending on versions.
