### ISSUE TITLE
Clash between url rewrites and blog URLs

### ISSUE THREAD

**Issue by maaarghk** [bentideswell/magento2-wordpress-integration#124]
Hi,

I can't seem to find any other issues referring to this which I find a bit surprising, so perhaps we have a configuration problem here with another module - would be good to get some advice.

We have a site with a catalog category at the url www.example.com/fathers-day. We also have a wordpress tag with url fathers-day. 

When visiting www.example.com/blog/tag/fathers-day, the catalog URL is taking precedence.

I feel like I expect this, since the catalog URL is handled by Magento_UrlRewrite, which adds itself to RouterList with priority 20, whereas FishPig_WordPress adds itself with priority 99, so if any part of the URL is handled by UrlRewrite it will take precedence.

Is there a good solution here, since ultimately the FishPig url has high specificity? Raising FishPig_WordPress sortOrder seems bad, as although the router will fail the prefix check and exit early, it will still make an unnecessary connection to the wp database as part of the integration tests and I'd like to avoid that. 

What Magento expects as best practice is to generate entries in the url rewrites table to module/controller/action type urls on a cron rather than using your own router. Assuming I've not missed something, any chance of a refactor? 

Cheers,

Mark

**Comment by bentideswell** [comment]
Hi Mark,

This doesn't sound like an issue with FishPig/WordPress, but it does sound like an issue with Magento. If you have a URL rewrite setup automatically for a category at /fathers-day, this should NOT match against /blog/tag/fathers-day as the path info here is incorrect.

I've tested this on a 2.4.6 install and I do not get the functionality that you are seeing. If I take a valid URL from the URL rewrites table (eg. /red-coat.html) and then append something at the start (eg. /testing/red-coat.html) I get a 404, which is the correct functionality.

If I created a URL in WordPress to match (eg. /blog/white-coat.html) then this would be picked up by FishPig and the WordPress content would display.

My guess is that you have a module in Magento that tries to be clever and send incorrectly typed URLs to the right one and this module is causing your issue.

I will close this comment, as I don't think this is a FishPig issue, but if you have any more evidence that FishPig is at issue and can replicate the issue on a Magento install with no other modules, please re-open and send over the info.

Thanks!
