### ISSUE TITLE
Integration Tests running on every page load 

### ISSUE THREAD

**Issue by SamJUK** [bentideswell/magento2-wordpress-integration#125]
We have a client with a Magento 2 store using Fishpig with the feature products module to connect with their externally hosted blog.

We've noticed FishPig is running its integration tests on seemingly every page request (including post routes). 
Increasing page load time on pages unrelated to the blog, especially when the blog is under high load.

From a quick look at the code in `FishPig\WordPress\App\View\AssetProvider`. It appears we don't check if the assetProviders apply to the current request, instead this is done in the actual `provideAssets` method instead, which causes the integration tests to run before hand.

Looking at the related products assets provider, the `provideAssets` method starts with a early return that checks if the shortcode is present. If that was extracted into a new method like `requestContainsAssets`, we could filter the assetProviderPool in `FishPig\WordPress\App\View\AssetProvider::provideAssets` by that method to check if any of the providers apply to the actual request before we run the integration tests.

<img width="903" alt="routes" src="https://github.com/bentideswell/magento2-wordpress-integration/assets/7872420/e5f3566b-c22e-4fe8-b561-651e66f11c01">

![trace1](https://github.com/bentideswell/magento2-wordpress-integration/assets/7872420/450338f3-a55a-4d61-825c-1e7951887b0c)
![trace2](https://github.com/bentideswell/magento2-wordpress-integration/assets/7872420/e96c6d67-3311-4e74-9a47-e60166d05a5f)

**Comment by SamJUK** [comment]
Identified the large amount of API requests being due to the Fishpig cache being disabled on production (whoops). So the Integration data was never being cached.

That aside, still do we need to be running the integration tests on every page even when it doesn't contain fishpig assets/widgets? Such as checkout / loginPost etc.

**Comment by bentideswell** [comment]
Hi @SamJUK, thanks for the info and detail. You didn't mention your module version, so I am guessing it's an older version. Version 3.28.2 introduced the always enabled caching system, so this version should resolve the issue you see with the integration tests taking some time to run as it auto enables the cache and it is not possible to disable it. Once these tests have been executed once and cached, the future reoccurences take very little time to complete, as it just checks the cache.

That being said, we always want to improve the module and make it more efficient, so I have refactored the AssetProvider to use the canProvideAssets($request, $response): bool method. This was method was available for most asset providers already, but generally an internal private method. This is now public and is called via the main AssetProvider to determine whether there are any asset providers that need to run.

Each asset provider (there's around 10 in total, spread through out the different modules), now all properly check whether they should run and report it via the canProvideAssets method.

Updating all installed FishPig/WP modules should resolve the issues you are seeing, so I will close this issue. If you find the issues still exist, or new but related issues have now been introduced then please feel free to re-open this issue and report back.

**Comment by SamJUK** [comment]
Amazing, yeah the current version that is running will be a few behind. 

What we did notice while testing originally, was the CSPCollector plugin also was another reason for the integrationTests to be run on every page. It would be nice if we could identify if the page contains any FishPig blocks before we add the policies to the page.

**Comment by bentideswell** [comment]
I've just pushed version 3.28.17 and this includes caching on the CSP policy generator. This means that the first run of the policy generation process will run the integration tests (which have probably already been cached by another request, so should be fast), but all future requests won't run them. Hopefully this helps with your issues, but if you spot anything else then please let me know!
