### ISSUE TITLE
Submitting a comment to a post not working

### ISSUE THREAD

**Issue by SatishDubariya** [bentideswell/magento2-wordpress-integration#14]
![screenshot from 2016-08-16 15 11 25](https://cloud.githubusercontent.com/assets/21054477/17694930/d5c4b938-63c3-11e6-96ba-d6f17cdc37d6.png)
**comment reply url wrong...**
![screenshot from 2016-08-16 13 45 12](https://cloud.githubusercontent.com/assets/21054477/17692549/d512b2b2-63b7-11e6-94ac-99cce5276c27.png)
**form action url wrong**
**comment_post_ID field value empty**
While submittin comment to a post...it not works

**Comment by bentideswell** [comment]
This has been fixed in commit fddbfc2.
