### ISSUE TITLE
Full Page Cache not cleared

### ISSUE THREAD

**Issue by maderlock** [bentideswell/magento2-wordpress-integration#16]
Although block cache is cleared, when there is a new blog post there does not seem to be any way to clear the relevant full-page cache entry, so the entire full page cache has to be cleared.

**Comment by bentideswell** [comment]
It's not possible to automatically do this. Events in WordPress (such as creating or editing a blog post) cannot be heard in Magento so it is impossible to add code into Magento to react to them.

**Comment by maderlock** [comment]
If not automatically, how about a way to do this manually?
