### ISSUE TITLE
Not working - magento 2.1.1

### ISSUE THREAD

**Issue by santhoshnsscoe** [bentideswell/magento2-wordpress-integration#18]
I am using magento 2.1.1 and the wordpress intergration is not at all working. Is this module complete or under process only.
Used the wordpress intergration for magento 1. That is working fine.

**Comment by bentideswell** [comment]
The extension is stable and working correctly. Please provide more information on how it is not working.

Have you followed the read me?

https://github.com/bentideswell/magento2-wordpress-integration/blob/master/README.md

Do you have any errors in the Magento Admin WordPress section? If not, this should give you your blog URL that you can use to access the integrated blog.

GitHub is for posting specific bugs and not for general support requests. I will close this issue. You may have already done so but if not, please send a support request through https://fishpig.co.uk/.

If you have already sent one, I will be going through these in an hour's time, however please send a new ticket with the answers to the questions I have included above.

**Comment by santhoshnsscoe** [comment]
I got it working. Did lots of debug. 
I would suggest you to show the errors. It was not showing any errors.

FishPig\WordPress\Helper\Theme 
public function validate()
There are some errors and these should be shown to the customer.
``
'The FishPig WordPress theme is not installed. <a href="?install-theme=1">Click here to install it</a>.'
'Unable to install a WordPress theme file due to permissions. File is ' . $targetFile
``

It is not coming due to multiple try and catch in FishPig\WordPress\Controller\Router and FishPig\WordPress\Model\App
``
if (!$this->_app->canRun()) {
    return false;
}
``

Also, i am using Mirasvit\Core\Controller\Router which is using sortOrder 50. So, had to change FishPig\WordPress\Controller\Router to sortOrder 49.

Thanks for the module. It works super after these changes. Please update the code to show the error messages properly. And, change or tell user to check if they are using Magento\Framework\App\RouterList

**Comment by anhtdt** [comment]
![Screenshot from 2021-02-04 09-53-38](https://user-images.githubusercontent.com/59239959/106838451-e9fe8600-66ce-11eb-8dea-b39953bbc40c.png)
Can you help me ?
I install PigFish_Wordpress to magento 2. Admin show error in picture. I don't know which steps I'm missing. Thank you

**Comment by bentideswell** [comment]
Hi @anhtdt, if you read the error message, it tells you the issue and how to fix it.

Issue: The FishPig WordPress theme is installed but is not acitve
Solution: login to the WordPress Admin and enable it

To paraphrase, the integration module has been able to automatically install a theme in WordPress called FishPig. This theme is required for the integration to work. The module has installed this but has not automatically enabled it so to proceed you need to manually enable the theme.

To do this, login to the WordPress Admin and select Appearances > Themes and click the Activate link under the FishPig theme.

You can delete any other installed themes.

**Comment by anhtdt** [comment]
> Hi @anhtdt, if you read the error message, it tells you the issue and how to fix it.
> 
> Issue: The FishPig WordPress theme is installed but is not acitve
> Solution: login to the WordPress Admin and enable it
> 
> To paraphrase, the integration module has been able to automatically install a theme in WordPress called FishPig. This theme is required for the integration to work. The module has installed this but has not automatically enabled it so to proceed you need to manually enable the theme.
> 
> To do this, login to the WordPress Admin and select Appearances > Themes and click the Activate link under the FishPig theme.
> 
> You can delete any other installed themes.

Thank you. It miss step active theme FishPg. it worked
