### ISSUE TITLE
"Leave Your Reply" Form validation

### ISSUE THREAD

**Issue by SatishDubariya** [bentideswell/magento2-wordpress-integration#19]
Magento Validation in Leave your reply form fields are missing. So while Submit form with enter any field value it redirects to http://localhost/magento/wp/wp-comments-post.php page and display error : ERROR: please fill the required fields (name, email).
![comment submission failure](https://cloud.githubusercontent.com/assets/21054477/19104095/4069c3ae-8af8-11e6-9720-9da43a3e4a55.png)

**Comment by SatishDubariya** [comment]
I have solved this by adding data-mage-init='{"validation": {}}' attribute in form.
<form id="respond" method="post" action="<?php echo $this->getCommentFormAction() ?>" **data-mage-init='{"validation": {}}'** class="form">
And also add class **required-entry** in form fields which i want to be required.

**Comment by SatishDubariya** [comment]
I have solved this by adding **data-mage-init='{"validation": {}}'** attribute in form tag.
And add class **required-entry** in form fields which  iwant to be required.

**Comment by bentideswell** [comment]
Hi Satish,

Can you submit a pull request for this, please?

*Ben Tideswell*

*FishPig <*http://fishpig.co.uk/>
Professional Magento development & web design
