### ISSUE TITLE
Blog not integrated properly

### ISSUE THREAD

**Issue by annagreen-juicymedia** [bentideswell/magento2-wordpress-integration#20]
Hi,

I've set up wordpress within my Magento 2 area and set the site  address to be http://highonbikes2.tmpsvr5.co.uk/blog within my wordpress but when I view this page on the front end I get a Magento 404 error?

The installation directory is /wp and I have followed the instructions for setting the module up from https://github.com/bentideswell/magento2-wordpress-integration/blob/master/README.md

**Comment by leembrooks** [comment]
Just to confirm, I have the same problem with Magento 2.1.1 and 2.1.2.
Any insight as to how to solve this would be greatly appreciated.

Just to add, I also had to manually run a bunch of Magento shell commands to get the plugin to register at all which aren't currently mentioned in the documentation.

**Comment by cashgrow** [comment]
Can you specify the shell commands? having a hard time installing it on 2.1.. 
tried enabling it in the admin.. but it says "update pending"

**Comment by annagreen-juicymedia** [comment]
Have you run the setup:upgrade command and re-compiled?

**Comment by leembrooks** [comment]
@cashgrow 

I ran the below and the module then appeared in the admin.

bin/magento module:enable FishPig_WordPress
bin/magento setup:upgrade
bin/magento setup:static-content:deploy

One thing that caught me out is Magento's caching - it seems a lot more aggressive that in Magento 1.9 and it took a full purge for the /blog link to then start working.

**Comment by cashgrow** [comment]
Thanks! 
Ran the commands above! worked like a charm.. :)  just took some time for it to re-cache
Also have the rewrite problem with /blog

**Comment by leembrooks** [comment]
You're more than welcome!

**Comment by leembrooks** [comment]
@cashgrow if you're having that issue.. go into the Wordpress page in the Magento admin, append 
"?install-theme=1" to the url and hit enter.

It'll appear as though nothing has happened. 
Then go into the wp-admin, set the "FishPig integration theme" as the Wordpress default, completely flush your Magento cache and you should be on to a winner.

**Comment by cashgrow** [comment]
Thats beautiful!!! great! owe u guys a beer or something :) :)

**Comment by annagreen-juicymedia** [comment]
Thanks! That solved the problem perfectly!
