### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by kevljones** [bentideswell/magento2-wordpress-integration#21]
Hi.

We have used the Wordpress Integration successfully on a Magento 1.9.2.4 platform for a while. We are in the process of upgrading to 2.1.1 but after installing the extension via command line we get errors when trying to compile after the installation. The error I get is

Repositories code generation... 1/7 [====>-----------------------]  14% 1 sec 44.0 MiBSegmentation fault

After removing the extension I can recompile without any issues.

Was wondering if you had encountered this problem before?

Thanks

Kev

**Comment by philcook** [comment]
I also have a compile error but slightly different. This is on Magento CE 2.1.2.

```
php bin/magento setup:di:compile
Compilation was started.
Repositories code generation... 1/7 [====>-----------------------]  14% 1 sec 75.5 MiB
PHP Fatal error:  Cannot redeclare class FishPig\WordPress\Api\Data\Entity\ViewableInterface in /app/code/FishPig/Wordpress/Api/Data/Entity/ViewableInterface.php on line 12

Fatal error: Cannot redeclare class FishPig\WordPress\Api\Data\Entity\ViewableInterface in /app/code/FishPig/Wordpress/Api/Data/Entity/ViewableInterface.php on line 12
```

Any ideas what is the issue here?

**Comment by bentideswell** [comment]
Can you provide any more information? I cannot recreate this issue and can compile successfully.

**Comment by bentideswell** [comment]
I'm closing this issue as no more information has been provided and I am unable to recreate the problem. Compilation works fine on my various test installations.

If you have more information, please re-open the issue and provide it.
