### ISSUE TITLE
Error in Magento 2 admin.

### ISSUE THREAD

**Issue by Calraiser** [bentideswell/magento2-wordpress-integration#22]
Hi !

This plugin not working for me. 
The installation its ok, but in Magento 2 admin I have an error. 

a:4:{i:0;s:37:"Object DOMDocument should be created."....

Thanks in advance, 

Regards, 

Carlos.

**Comment by bentideswell** [comment]
Please provide more information.

Is this on every page in the Admin or just the WordPress configuration section?
Did you get a chance to configure the extension before seeing this page?
Have you disabled the cache and compiler?
