### ISSUE TITLE
i got error when i check categories as dropdown

### ISSUE THREAD

**Issue by nihachi** [bentideswell/magento2-wordpress-integration#24]
Exception in FishPig\WordPress\Block\Sidebar\Widget\Categories

Class wordpress does not exist
# 0 C:\xampp\htdocs\royal-garden\vendor\magento\framework\Code\Reader\ClassReader.php(19): ReflectionClass->__construct('wordpress')
# 1 C:\xampp\htdocs\royal-garden\vendor\magento\framework\ObjectManager\Definition\Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('wordpress')
# 2 C:\xampp\htdocs\royal-garden\vendor\magento\framework\ObjectManager\Factory\Dynamic\Developer.php(71): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('wordpress')
# 3 C:\xampp\htdocs\royal-garden\vendor\magento\framework\ObjectManager\ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('wordpress')
# 4 C:\xampp\htdocs\royal-garden\vendor\magento\framework\View\TemplateEngine\Php.php(122): Magento\Framework\ObjectManager\ObjectManager->get('wordpress')
# 5 C:\xampp\htdocs\royal-garden\app\code\FishPig\WordPress\view\frontend\templates\sidebar\widget\categories.phtml(22): Magento\Framework\View\TemplateEngine\Php->helper('wordpress')
# 6 C:\xampp\htdocs\royal-garden\vendor\magento\framework\View\TemplateEngine\Php.php(59): include('C:\xampp\htdocs...')
# 7 C:\xampp\htdocs\royal-garden\vendor\magento\framework\View\Element\Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(FishPig\WordPress\Block\Sidebar\Widget\Categories), 'C:/xampp/htdocs...', Array)
# 8 C:\xampp\htdocs\royal-garden\vendor\magento\framework\View\Element\Template.php(279): Magento\Framework\View\Element\Template->fetchView('C:/xampp/htdocs...')
# 9 C:\xampp\htdocs\royal-garden\vendor\magento\framework\View\Element\AbstractBlock.php(659): Magento\Framework\View\Element\Template->_toHtml()
# 10 C:\xampp\htdocs\royal-garden\app\code\FishPig\WordPress\Block\AbstractBlock.php(39): Magento\Framework\View\Element\AbstractBlock->toHtml()
# 11 C:\xampp\htdocs\royal-garden\vendor\magento\framework\View\Layout.php(542): FishPig\WordPress\Block\AbstractBlock->toHtml()
# 12 C:\xampp\htdocs\royal-garden\vendor\magento\framework\View\Layout.php(518): Magento\Framework\View\Layout->_renderBlock('sidebar\widget\...')
# 13 C:\xampp\htdocs\royal-garden\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('sidebar\widget\...')
# 14 C:\xampp\htdocs\royal-garden\vendor\magento\framework\View\Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('sidebar\widget\...')
# 15 C:\xampp\htdocs\royal-garden\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('sidebar\widget\...', true)
# 16 C:\xampp\htdocs\royal-garden\vendor\magento\framework\View\Element\AbstractBlock.php(503): Magento\Framework\View\Layout\Interceptor->renderElement('sidebar\widget\...', true)
# 17 [internal function]: Magento\Framework\View\Element\AbstractBlock->getChildHtml()
# 18 C:\xampp\htdocs\royal-garden\vendor\magento\framework\View\TemplateEngine\Php.php(82): call_user_func_array(Array, Array)
# 19 C:\xampp\htdocs\royal-garden\app\code\FishPig\WordPress\view\frontend\templates\sidebar.phtml(13): Magento\Framework\View\TemplateEngine\Php->__call('getChildHtml', Array)
# 20 C:\xampp\htdocs\royal-garden\app\code\FishPig\WordPress\view\frontend\templates\sidebar.phtml(13): Magento\Framework\View\TemplateEngine\Php->getChildHtml()
# 21 C:\xampp\htdocs\royal-garden\vendor\magento\framework\View\TemplateEngine\Php.php(59): include('C:\xampp\htdocs...')
# 22 C:\xampp\htdocs\royal-garden\vendor\magento\framework\View\Element\Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(FishPig\WordPress\Block\Sidebar), 'C:/xampp/htdocs...', Array)
# 23 C:\xampp\htdocs\royal-garden\vendor\magento\framework\View\Element\Template.php(279): Magento\Framework\View\Element\Template->fetchView('C:/xampp/htdocs...')
# 24 C:\xampp\htdocs\royal-garden\vendor\magento\framework\View\Element\AbstractBlock.php(659): Magento\Framework\View\Element\Template->_toHtml()
# 25 C:\xampp\htdocs\royal-garden\app\code\FishPig\WordPress\Block\AbstractBlock.php(39): Magento\Framework\View\Element\AbstractBlock->toHtml()
# 26 C:\xampp\htdocs\royal-garden\vendor\magento\framework\View\Layout.php(542): FishPig\WordPress\Block\AbstractBlock->toHtml()
# 27 C:\xampp\htdocs\royal-garden\vendor\magento\framework\View\Layout.php(518): Magento\Framework\View\Layout->_renderBlock('wp.sidebar')
# 28 C:\xampp\htdocs\royal-garden\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('wp.sidebar')
# 29 C:\xampp\htdocs\royal-garden\vendor\magento\framework\View\Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('wp.sidebar')
# 30 C:\xampp\htdocs\royal-garden\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('wp.sidebar', true)
# 31 C:\xampp\htdocs\royal-garden\vendor\magento\framework\View\Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('wp.sidebar')
# 32 C:\xampp\htdocs\royal-garden\vendor\magento\framework\View\Layout.php(520): Magento\Framework\View\Layout->_renderContainer('content')
# 33 C:\xampp\htdocs\royal-garden\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('content')
# 34 C:\xampp\htdocs\royal-garden\vendor\magento\framework\View\Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
# 35 C:\xampp\htdocs\royal-garden\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('content', true)
# 36 C:\xampp\htdocs\royal-garden\vendor\magento\framework\View\Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('content')
# 37 C:\xampp\htdocs\royal-garden\vendor\magento\framework\View\Layout.php(520): Magento\Framework\View\Layout->_renderContainer('main')
# 38 C:\xampp\htdocs\royal-garden\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main')
# 39 C:\xampp\htdocs\royal-garden\vendor\magento\framework\View\Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main')
# 40 C:\xampp\htdocs\royal-garden\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main', true)
# 41 C:\xampp\htdocs\royal-garden\vendor\magento\framework\View\Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('main')
# 42 C:\xampp\htdocs\royal-garden\vendor\magento\framework\View\Layout.php(520): Magento\Framework\View\Layout->_renderContainer('columns')
# 43 C:\xampp\htdocs\royal-garden\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('columns')
# 44 C:\xampp\htdocs\royal-garden\vendor\magento\framework\View\Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('columns')
# 45 C:\xampp\htdocs\royal-garden\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('columns', true)
# 46 C:\xampp\htdocs\royal-garden\vendor\magento\framework\View\Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('columns')
# 47 C:\xampp\htdocs\royal-garden\vendor\magento\framework\View\Layout.php(520): Magento\Framework\View\Layout->_renderContainer('main.content')
# 48 C:\xampp\htdocs\royal-garden\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.content')
# 49 C:\xampp\htdocs\royal-garden\vendor\magento\framework\View\Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.content')
# 50 C:\xampp\htdocs\royal-garden\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.content', true)
# 51 C:\xampp\htdocs\royal-garden\vendor\magento\framework\View\Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('main.content')
# 52 C:\xampp\htdocs\royal-garden\vendor\magento\framework\View\Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
# 53 C:\xampp\htdocs\royal-garden\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
# 54 C:\xampp\htdocs\royal-garden\vendor\magento\framework\View\Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
# 55 C:\xampp\htdocs\royal-garden\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', true)
# 56 C:\xampp\htdocs\royal-garden\vendor\magento\framework\View\Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
# 57 C:\xampp\htdocs\royal-garden\vendor\magento\framework\View\Layout.php(520): Magento\Framework\View\Layout->_renderContainer('root')
# 58 C:\xampp\htdocs\royal-garden\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
# 59 C:\xampp\htdocs\royal-garden\vendor\magento\framework\View\Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
# 60 C:\xampp\htdocs\royal-garden\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
# 61 C:\xampp\htdocs\royal-garden\vendor\magento\framework\View\Layout.php(938): Magento\Framework\View\Layout\Interceptor->renderElement('root')
# 62 C:\xampp\htdocs\royal-garden\vendor\magento\framework\Interception\Interceptor.php(146): Magento\Framework\View\Layout->getOutput()
# 63 C:\xampp\htdocs\royal-garden\var\generation\Magento\Framework\View\Layout\Interceptor.php(494): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
# 64 C:\xampp\htdocs\royal-garden\vendor\magento\framework\View\Result\Page.php(243): Magento\Framework\View\Layout\Interceptor->getOutput()
# 65 C:\xampp\htdocs\royal-garden\vendor\magento\framework\View\Result\Layout.php(164): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
# 66 C:\xampp\htdocs\royal-garden\vendor\magento\framework\Interception\Interceptor.php(74): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
# 67 C:\xampp\htdocs\royal-garden\vendor\magento\framework\Interception\Chain\Chain.php(70): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
# 68 C:\xampp\htdocs\royal-garden\vendor\magento\framework\Interception\Chain\Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-varnish-...')
# 69 C:\xampp\htdocs\royal-garden\vendor\magento\module-page-cache\Model\Controller\Result\VarnishPlugin.php(74): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
# 70 C:\xampp\htdocs\royal-garden\vendor\magento\framework\Interception\Chain\Chain.php(67): Magento\PageCache\Model\Controller\Result\VarnishPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
# 71 C:\xampp\htdocs\royal-garden\vendor\magento\framework\Interception\Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-builtin-...')
# 72 C:\xampp\htdocs\royal-garden\vendor\magento\module-page-cache\Model\Controller\Result\BuiltinPlugin.php(67): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
# 73 C:\xampp\htdocs\royal-garden\vendor\magento\framework\Interception\Interceptor.php(142): Magento\PageCache\Model\Controller\Result\BuiltinPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
# 74 C:\xampp\htdocs\royal-garden\var\generation\Magento\Framework\View\Result\Page\Interceptor.php(130): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
# 75 C:\xampp\htdocs\royal-garden\vendor\magento\framework\App\Http.php(139): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
# 76 C:\xampp\htdocs\royal-garden\vendor\magento\framework\App\Bootstrap.php(258): Magento\Framework\App\Http->launch()
# 77 C:\xampp\htdocs\royal-garden\index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
# 78 {main}

**Comment by bentideswell** [comment]
This is now fixed.
