### ISSUE TITLE
FishPig Magento2 issue (localhost/magento2/blog results in 404 page in frontend)

### ISSUE THREAD

**Issue by NikhilCPatil** [bentideswell/magento2-wordpress-integration#25]
The fishpig magento2 module is succesfully installed in the backend without any error but goes to 404 in the frontend , no post are seen on the frontend. Trying this from last evening , cant figure out wats wrong .

**Comment by NikhilCPatil** [comment]
is there any update??

**Comment by agonora** [comment]
Yes, same here.

http://www.domain.com/blog goes to 404

**Comment by dannyhajj** [comment]
Had the same issue here. There seem to be 2 undocumented steps that need to done.

1. After installing everything, go to http://www.example.com/blog/?install-theme=1  
  This step will create the necessary files for a theme called FishPig for WordPress. The wordpress themes directory needs to writable.  
  ref: https://github.com/bentideswell/magento2-wordpress-integration/blob/074c8d03333cecd111d7b5b0efdec14aa1563b52/Helper/Theme.php#L52
2. Go to the WordPress admin interface and enable the FishPig theme.

**Comment by agonora** [comment]
@dannyhajj thanks for sharing.

Im still seeing 404 when I access this http://www.example.com/blog/?install-theme=1 but what i did was copy the theme folder located in app/code/FishPig/WordPress/wptheme to wp/wp-content/themes/ and changed the theme in WP admin to FishPig theme. Now its working.

**Comment by bentideswell** [comment]
Sorry, this wasn't documented as it's supposed to walk you through this via the Magento Admin  > WordPress menu option. There was a bug in the extension preventing this. I have just pushed an update that fixes this issue.
