### ISSUE TITLE
Missing "...WordPress menu option..."

### ISSUE THREAD

**Issue by robohaus** [bentideswell/magento2-wordpress-integration#26]
Hi,

I cannot locate the WordPress menu option in my Magento 2.1.2 admin panel? i have...

1) Copied the extension files to app/code/FishPig/WordPress
2) Ran magento setup:di:compile
3) Flushed the cache

Can someone spell out the icon / selection path to display the WordPress menu?

Note:

- I did not use WP or BLOG in my WP filepaths during installation of WordPress.

Regards
Michael

**Comment by bentideswell** [comment]
Did you enable the module?

Run the following commands:

rm -rf var/cache/*
rm -rf var/di/*
rm -rf var/generation/*
php bin/magento module:enable FishPig_WordPress

Log out and back in to the Magento 2 Admin. You should see a WordPress icon in the left hand navigation menu. If not, you haven't installed the extension correctly.
