### ISSUE TITLE
Post type not pulling through from Model/Post/Type.php

### ISSUE THREAD

**Issue by gavinlimely** [bentideswell/magento2-wordpress-integration#27]
On line 315 of https://github.com/bentideswell/magento2-wordpress-integration/blob/master/Model/Post/Type.php, should this be $this->_getData('post_type') instead of $this->_getData('name')? 

The latest versions Permalinks doesn't seem to work unless I change this.

**Comment by bentideswell** [comment]
Permalinks are working fine for me.

I know it seems odd but WordPress stores the post type using an array key of 'name'. The actual name of the post type (eg. Article as opposed to article) is stored in labels/name.

The getPostType() method should return the unique post type identifier (eg. article or post).

If you can provide any more information for me to recreate the issue, I'd be happy to keep looking.

**Comment by gavinlimely** [comment]
I literally just installed the latest version of Wordpress & the permalinks wouldn't work without me changing that file. The links were showing as the GUID.

**Comment by bentideswell** [comment]
I have found the issue and you were correct, however the fix is slightly different (for compatibility with other modules). I have just pushed an update to Git that fixes this.
