### ISSUE TITLE
Database connection error on non Wordpress pages

### ISSUE THREAD

**Issue by gavinlimely** [bentideswell/magento2-wordpress-integration#28]
Hello,

I'm getting a wordpress connection error on non Wordpress pages when trying to pull out posts on any page that isn't powered by Fishpig.

A temporary solution was for me to change the constructor of app/code/FishPig\WordPress\Model\ResourceModel\Collection\AbstractCollection to be : 

`   

            $this->_app = $wpContext->getApp();
            
            /**
             * @todo - added in as a temporary fix
             */
            $this->_app->init();
        
	    parent::__construct($entityFactory, $logger, $fetchStrategy, $eventManager, $connection, $resource);
           
`

This makes sure that the Wordpress resource is always initialised.

Cheers

**Comment by bentideswell** [comment]
The resources/collection should work with a lazy connection type so that they only connect when needed.

Can you provide any info for me to recreate this issue? The file you referenced isn't referenced on non-WP pages for me and no error is reported.

**Comment by gavinlimely** [comment]
Ahh sorry. I was trying to pull out latest posts on the homepage of Magento2. 

I created a FishPig\WordPress\Block\Post\ListPost on the homepage, I got the error when calling the getPosts method in the template file. It's asif the Wordpress connection wasn't initialised prior.

**Comment by bentideswell** [comment]
Hi Gavin,

I have fixed this issue now and released an update to Git.
