### ISSUE TITLE
Compile error on add_action()

### ISSUE THREAD

**Issue by Colir** [bentideswell/magento2-wordpress-integration#29]
Hi.
I 'm getting this error when trying to setup:di:compile

Can you please help me ? thank you

`Compilation was started.
Repositories code generation... 1/7 [====>-----------------------]  14% 1 sec 36.0 MiBPHP Fatal error:  Uncaught Error: Call to undefined function add_action() in /Users/Colir/Works/HorsePilot/www/magento/app/code/FishPig/WordPress/wptheme/cpt.php:168
Stack trace:
#0 /Users/Colir/Works/HorsePilot/www/magento/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(70): require_once()
#1 /Users/Colir/Works/HorsePilot/www/magento/setup/src/Magento/Setup/Module/Di/App/Task/Operation/RepositoryGenerator.php(61): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->getList('/Users/Colir/Wo...')
#2 /Users/Colir/Works/HorsePilot/www/magento/setup/src/Magento/Setup/Module/Di/App/Task/Manager.php(56): Magento\Setup\Module\Di\App\Task\Operation\RepositoryGenerator->doOperation()
#3 /Users/Colir/Works/HorsePilot/www/magento/setup/src/Magento/Setup/Console/Command/DiCompileCommand.php(206): Magento\Setup\Module\Di\App\Task\Manager->process(Object(Closure), Object(Closure))
#4 /Users/Colir/Works/HorsePilot/www/magento/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Magento\Setup\Console\Com in /Users/Colir/Works/HorsePilot/www/magento/app/code/FishPig/WordPress/wptheme/cpt.php on line 168

Fatal error: Uncaught Error: Call to undefined function add_action() in /Users/Colir/Works/HorsePilot/www/magento/app/code/FishPig/WordPress/wptheme/cpt.php:168
Stack trace:
#0 /Users/Colir/Works/HorsePilot/www/magento/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(70): require_once()
#1 /Users/Colir/Works/HorsePilot/www/magento/setup/src/Magento/Setup/Module/Di/App/Task/Operation/RepositoryGenerator.php(61): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->getList('/Users/Colir/Wo...')
#2 /Users/Colir/Works/HorsePilot/www/magento/setup/src/Magento/Setup/Module/Di/App/Task/Manager.php(56): Magento\Setup\Module\Di\App\Task\Operation\RepositoryGenerator->doOperation()
#3 /Users/Colir/Works/HorsePilot/www/magento/setup/src/Magento/Setup/Console/Command/DiCompileCommand.php(206): Magento\Setup\Module\Di\App\Task\Manager->process(Object(Closure), Object(Closure))
#4 /Users/Colir/Works/HorsePilot/www/magento/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Magento\Setup\Console\Com in /Users/Colir/Works/HorsePilot/www/magento/app/code/FishPig/WordPress/wptheme/cpt.php on line 168
MBP-Cyril:magento Colir$ `

**Comment by bentideswell** [comment]
I have just pushed a commit to GIT that fixes this issue.
