### ISSUE TITLE
Wordpress table prefix

### ISSUE THREAD

**Issue by clivewalkden** [bentideswell/magento2-wordpress-integration#3]
One of our developers installed Wordpress with a non-default table prefix (somethingelsewp_) and the plugin reports an sql error in the admin system.

**Comment by bentideswell** [comment]
The extension should read the table prefix from the wp-config.php file automatically. What error are you getting? Have you defined $table_prefix in wp-config.php?

**Comment by clivewalkden** [comment]
The error was displaying the failed sql and it showed the prefix as wp_ when the wp_config.php file had the setting of somethingelse_.

I don't have the full error message to hand as it was on a colleagues machine and we've switched it back to default for now, I'll see if i can replicate.

**Comment by bentideswell** [comment]
Clive, would it be possible to send over your wp-config.php file so I can test it please? This would help me debug the issue and improve the parsing of this file. Obviously you're welcome to change the username, database name and password to something else for security reasons.

**Comment by clivewalkden** [comment]
Sorry for the delay, here is a screenshot of the error message. Done some further digging and this only shows if the wp_config $table_prefix is not the same as the tables. Not sure how we got the issue yesterday. Just might be nice to see a custom error rather than the sql output.

**Comment by bentideswell** [comment]
I'll try and add a better error message in here. I will close this for now but feel free to re-open if the extension is not picking up your custom table prefix.
