### ISSUE TITLE
PHP Error

### ISSUE THREAD

**Issue by SAN1TAR1UM** [bentideswell/magento2-wordpress-integration#31]
After enabling FishPig_WordPress I get a 500 error on the Magento frontend.

I also have the below message in my PHP error log:

```[Wed Nov 23 03:15:24.105222 2016] [:error] [pid 3123] [client 192.168.33.1:55415] PHP Fatal error:  Uncaught Error: Call to a member function select() on boolean in /var/www/html/magento2/app/code/FishPig/WordPress/Model/Config.php:55\nStack trace:\n#0 /var/www/html/magento2/var/generation/FishPig/WordPress/Model/Config/Interceptor.php(50): FishPig\\WordPress\\Model\\Config->getOption('siteurl')\n#1 /var/www/html/magento2/app/code/FishPig/WordPress/Model/App/Url.php(72): FishPig\\WordPress\\Model\\Config\\Interceptor->getOption('siteurl')\n#2 /var/www/html/magento2/app/code/FishPig/WordPress/Observer/InjectContent.php(42): FishPig\\WordPress\\Model\\App\\Url->getSiteurl()\n#3 /var/www/html/magento2/vendor/magento/framework/Event/Invoker/InvokerDefault.php(73): FishPig\\WordPress\\Observer\\InjectContent->execute(Object(Magento\\Framework\\Event\\Observer))\n#4 /var/www/html/magento2/vendor/magento/framework/Event/Invoker/InvokerDefault.php(61): Magento\\Framework\\Event\\Invoker\\InvokerDefault->_callObserverMethod(Object(FishPig\\WordPress\\Observer\\InjectContent), Object(Magento\\Framework\\Event\\Observer))\n#5 /var/www/html/magento2/ve in /var/www/html/magento2/app/code/FishPig/WordPress/Model/Config.php on line 55```

**Comment by bentideswell** [comment]
I have just pushed a commit (version 1.0.0.7) that fixes this issue.
