### ISSUE TITLE
Old Magento1 Code in FishPig\WordPress\Block\Post\View\Comment\Form.php

### ISSUE THREAD

**Issue by gavinlimely** [bentideswell/magento2-wordpress-integration#32]
Hi Ben,

Thanks for the other fixes. 

I've noticed that there is some old Magento Code in FishPig\WordPress\Block\Post\View\Comment\Form.php

See line 59

`!Mage::getSingleton('customer/session')->isLoggedIn();`

and 

Line 73

`Mage::getUrl()`

This is stopping the post view page from working..

Cheers

**Comment by bentideswell** [comment]
Hi @gavinlimely,

I have just pushed a new commit that fixes this.

Cheers!
