### ISSUE TITLE
Add to packagist & tag versions

### ISSUE THREAD

**Issue by adamj88** [bentideswell/magento2-wordpress-integration#33]
It would be much easier to install and manage the versions of this if it was pushed to https://packagist.org/ and each version was tagged with `git tag`.

A lot of open source magento 2 modules can be found this way - would you be open to this approach?

**Comment by bentideswell** [comment]
I have added this to packagist in what I believe is the correct way. You should be able to install it using:

    composer require fishpig/module-wordpress

This should install 1.0.0.8-stable, which is the latest version.

Can you give it a go and let me if it's working correctly, please?

**Comment by adamj88** [comment]
The `-stable` suffix on the tag seems to be throwing it off, composer conventions only seems to parse `v1.0.0.8` or `1.0.0.8` correctly as a tag, as well as `1.0.0.8-rc1` etc.

See: https://getcomposer.org/doc/02-libraries.md#tags

Much appreciated for adding this to packagist, thanks!

**Comment by bentideswell** [comment]
Sorry, I read that on a tutorial online. I have just tagged the branch with '1.0.0.9'. Is that any better?

**Comment by adamj88** [comment]
That's the one 👍 

Thanks a lot Ben :)
