### ISSUE TITLE
setup:di:compile Errors

### ISSUE THREAD

**Issue by dh1984** [bentideswell/magento2-wordpress-integration#34]
I get following errors when i do setup:di:compile on a magento 2.1.2 shop in developer mode:

Errors during compilation:
	FishPig\WordPress\Controller\Action
		Incorrect dependency in class FishPig\WordPress\Controller\Action in /htdocs/vendor/fishpig/module-wordpress/Controller/Action.php
\Magento\Framework\Controller\ResultFactory already exists in context object
Total Errors Count: 1
Errors during compilation:
	FishPig\WordPress\Controller\Action
		Incorrect dependency in class FishPig\WordPress\Controller\Action in /htdocs/vendor/fishpig/module-wordpress/Controller/Action.php
\Magento\Framework\Controller\ResultFactory already exists in context object
Total Errors Count: 1
Errors during compilation:
	FishPig\WordPress\Controller\Action
		Incorrect dependency in class FishPig\WordPress\Controller\Action in /htdocs/vendor/fishpig/module-wordpress/Controller/Action.php
\Magento\Framework\Controller\ResultFactory already exists in context object
Total Errors Count: 1
Errors during compilation:
	FishPig\WordPress\Controller\Action
		Incorrect dependency in class FishPig\WordPress\Controller\Action in /htdocs/vendor/fishpig/module-wordpress/Controller/Action.php
\Magento\Framework\Controller\ResultFactory already exists in context object
Total Errors Count: 1
Errors during compilation:
	FishPig\WordPress\Controller\Action
		Incorrect dependency in class FishPig\WordPress\Controller\Action in /htdocs/vendor/fishpig/module-wordpress/Controller/Action.php
\Magento\Framework\Controller\ResultFactory already exists in context object
Total Errors Count: 1
Errors during compilation:
	FishPig\WordPress\Controller\Action
		Incorrect dependency in class FishPig\WordPress\Controller\Action in /htdocs/vendor/fishpig/module-wordpress/Controller/Action.php
\Magento\Framework\Controller\ResultFactory already exists in context object
Total Errors Count: 1

**Comment by bentideswell** [comment]
This should now be fixed!
