### ISSUE TITLE
AbstractBlock Exception handling

### ISSUE THREAD

**Issue by pushonscott** [bentideswell/magento2-wordpress-integration#35]
I have extended your Abstract block to add some custom functionality to our home page, however if i try to load a product that doesn't exist, then magento throws a 'NoSuchEntityException'. Your block then catches this, throws another exception and exits.

`echo sprintf('<h1>Exception in %s</h1><p>%s</p><pre>%s</pre>', get_class($this), $e->getMessage(), $e->getTraceAsString());
exit;`

Any plans to log this exception instead? Ideally, i would like to try an load the product from my extended block class.

**Comment by bentideswell** [comment]
Hi Scott, sorry, I forgot that was in there. I have removed this code and pushed an update.
