### ISSUE TITLE
Shortcodes not working

### ISSUE THREAD

**Issue by cicero83** [bentideswell/magento2-wordpress-integration#36]
Hi,

My shortcodes are not working. I used this shortcode, but nothing is happening:
`[product id="67829"]`

And a question, are shortcodes from other plugins work in this installation?

Greetz

**Comment by danrcoull** [comment]
Also appears shortcodes seem to work in custom post types and acf fields but not standard pages and posts, though i can not see why due to the encryption on the addons.

**Comment by adamj88** [comment]
We're also seeing the `[product]` shortcode not working, there's no file in this modules `Shortcode/` directory for it, where there is for gallery, caption and oEmbed - all of which work.

Although there is a template for the product shortcode inside `view/frontend/templates/shortcode/product.phtml` - it looks to be untouched since the beta version of this extension.

Looks like it is still to be implemented, @bentideswell is this on your road map?

**Comment by bentideswell** [comment]
Sorry for the delay but yes this is on my road map.

Until then, you could look at including a Magento template like so:

    {{block type="Magento\Framework\View\Element\Template" 
      template="your/custom/template.phtml"
      product_ids="1,43,532,543"
    }}

Inside your custom template you could parse the product_ids, load products and display them however you wish.

**Comment by danrcoull** [comment]
`<?php
namespace SuttonSilver\WordpressProductPage\Shortcode;

class Product extends \FishPig\WordPress\Shortcode\AbstractShortcode
{

    protected $_productRepository;

    /**
     * Constructor
     **/
    public function __construct(
        \FishPig\WordPress\Model\App $app,
        \Magento\Framework\View\Element\Context $context,
        \Magento\Catalog\Api\ProductRepositoryInterfaceFactory $productRepositoryFactory
    )
    {
        $this->_app = $app;
        $this->_factory = $app->getFactory();
        $this->_layout = $context->getLayout();
        $this->_cache = $context->getCache();
        $this->_cacheState = $context->getCacheState();
        $this->_productRepository = $productRepositoryFactory;
    }

    /**
     * @return string
     **/
    public function getTag()
    {
        return 'product';
    }


    protected function _process()
    {
        $value = $this->getValue();
        if (($shortcodes = $this->_getShortcodesByTag($this->getTag())) !== false) {
            foreach ($shortcodes as $it => $shortcode) {
                $params = $shortcode->getParams();

                if (!$params->getSkus()) {
                    return $this;
                }

                if (($skus = trim($params->getSkus(), ',')) !== '') {
                    $products = array();
                    $skus = str_replace(array('&#8217;', '&#8242;'), '', utf8_encode($skus));
                    $repo = $this->_productRepository->create();
                    foreach (explode(',', $skus) as $sku) {
                        $products[] = $repo->get($sku);
                    }
                }

                $priceDefault = $this->_layout->createBlock('\Magento\Framework\Pricing\Render',
                    "product.price.render.default",
                    ["data" => ['price_render_handle' => 'catalog_product_prices', 'use_link_for_as_low_as'=>true]]
                );

                $price = $this->_layout->createBlock('\Magento\Catalog\Pricing\Render',
                    "product.price.tier",
                    ["data" => ['price_render' => 'product.price.render.default', 'price_type_code'=>'final_price','zone'=>'item_view']]
                )->setChild('child',$priceDefault);

                $html = $this->_layout->createBlock('\SuttonSilver\WordpressProductPage\Block\Frontend\Catalog\Product\View')
                    ->setTemplate('SuttonSilver_WordpressProductPage::shortcode/product.phtml')
                    ->addData($params->getData())
                    ->setObject($this->getObject())
                    ->setProducts($products)
                    ->setChild('child', $price)
                    ->toHtml();

                $this->setValue(str_replace($shortcode['html'], $html, $value));
            }
        }

        return $this;
    }
}


`

The above is pretty much a simple resolution to the problem.
