### ISSUE TITLE
Draft preview not working

### ISSUE THREAD

**Issue by git-reset--hard** [bentideswell/magento2-wordpress-integration#37]
Draft preview doesn't work in WP admin. It opens the "siteurl" with params like - blog/?p=793&preview=true
Which is basically the main page of the blog in Magento.

**Comment by pushonscott** [comment]
@git-reset--hard Do you know if this has been fixed?

**Comment by bentideswell** [comment]
I have just released an update that should fix this. I will close this issue but please reopen if the issue is not resolved.
