### ISSUE TITLE
Product post associations

### ISSUE THREAD

**Issue by arkadij-K** [bentideswell/magento2-wordpress-integration#43]
Hi,

We had a great experience working with your module in Magento 1.
Now we are migrating the website to Magento 2.
This feature is missing in Magento2 version - https://fishpig.co.uk/magento/wordpress-integration/product-post-associations/

**Comment by pascalwientjes** [comment]
+1

**Comment by rain2o** [comment]
We are in the same situation. Is this feature on the roadmap?

**Comment by bentideswell** [comment]
Yes this feature is on the roadmap and should be available sometime this year.

**Comment by clivewalkden** [comment]
Thanks for the update Ben, loving the development of this plugin!

**Comment by dharmendrakothe** [comment]
any updates on

**Comment by dharmendrakothe** [comment]
Need a fix to display Magento2 product on wordpress Fishpig

**Comment by Kershrew** [comment]
Any updates on this?
Thanks

**Comment by bentideswell** [comment]
This feature isn't available yet, at least not in the format it was for the Magento 1 version. That being said, you can include blocks in WordPress posts using the {{block format

    {{block class="Magento\Framework\View\Element\Template" name="Your.Block" product_ids="1,2,45,643" template="Magento_Blank::Modules\About.phtml"}}

Using the above code, you would need to change the template to point to your own custom template. In this template you could use the following to get the Product Ids passed:

    <?php if ($productIds = $this->getProductIds()): ?>
        <?php $productIds = explode(',', trim($productIds, ',')) ?>
        <?php if (count($productIds) > 0): ?>
            <pre><?php print_r($productIds) ?></pre>
        <?php endif; ?>
    <?php endif; ?>

You can then load a product model for each of the IDs and display the product however you want to.

**Comment by Kershrew** [comment]
Thanks @bentideswell 
I appreciate your example and will no doubt implement it, do you have a time frame on when proper product associations will be available? This method makes it quite difficult for the client to manage and would require our intervention for each blog post.

**Comment by bentideswell** [comment]
Sorry I don't have an accurate time frame at the minute.

**Comment by adamj88** [comment]
@bentideswell we're specifically interested in the ability to relate posts and display them on the product page as this was a useful feature of the M1 version.

Is there anything we can do to help facilitate this? I can imagine this is a pretty in depth solution which needs implementing - we would be happy to try and assist if we can put a plan in place for how to do so?

**Comment by Kershrew** [comment]
We created a solution using a shorthand which accepts an id (for a product) from wordpress, purchasing the wordpress shorthand and widgets plugin for the weltpixel integration and then outputting code similar to what bentideswell suggest above in a template in Magento, it is working well.

We do need to advise the clients to look up the id of a product in order to associate it but it doesn't seem to be a problem so far.

**Comment by josh-carter** [comment]
@bentideswell We had a requirement for this, I've just create PR #80  to implement similar functionality the the M1 extension. Let me know if you've got any issues with it.

**Comment by bentideswell** [comment]
This feature is now available:

https://fishpig.co.uk/magento/wordpress-integration/related-products/
