### ISSUE TITLE
Layout wordpress_homepage_view is overriden by wordpress_default

### ISSUE THREAD

**Issue by arkadij-K** [bentideswell/magento2-wordpress-integration#45]
I want tot change the page layout for the WP homepage to '_1column_'. But it is always loading in '_2columns-left_' which is specified in ***wordpress_default.xml***.
Though I can change page layout in *wordpress_default.xml* it will affect all the wordpress pages whilest I need to update only the homepage.
Does it appear to be a bug?
Is there any workaround?

**Comment by BenButterfield** [comment]
This was fixed in 1.0.0.36. Please check you have the latest version of the module.

**Comment by arkadij-K** [comment]
Confirm it fixed.
