### ISSUE TITLE
Issues with child blocks when overriding wordpress_term_view.xml

### ISSUE THREAD

**Issue by pushontom** [bentideswell/magento2-wordpress-integration#51]
`<block class="FishPig\WordPress\Block\Post\ListPost" name="wp.post.list" template="post/list.phtml">`
`<container name="wp.post.list.renderer" as="renderer">`

The code above does not get recognised when you copy `wordpress_term_view.xml` to your theme `FishPig_Wordpress/layout/override/base/wordpress_term_view.xml` 

This is due to the conditional statement not ever returning true from getChild:

Pull request to fix the issue: https://github.com/bentideswell/magento2-wordpress-integration/pull/50

**Comment by bentideswell** [comment]
Hi @pushontom, is this fixed now?
