### ISSUE TITLE
Does not seem to add blog pages to sitemap.xml

### ISSUE THREAD

**Issue by phillipmeyer** [bentideswell/magento2-wordpress-integration#55]
Hello,

I am sure that the Magento 1.x version used to automatically submit the blog pages to the sitemap but this does not appear to be happening with my version of the Magento 2 Fishpig extension.

**Comment by bentideswell** [comment]
Magento 2.3 finally adds support for easily adding items to the XML sitemap. This code is already in the extension. As soon as 2.3 is released, the code will start working and blog links will be added to the Magento XML sitemap.
