### ISSUE TITLE
Getting an error when try to load a Wordpress post

### ISSUE THREAD

**Issue by orbitrod** [bentideswell/magento2-wordpress-integration#6]
When loading a wordpress post, I get a "Front controller reached 100 router match iterations" error.  However I am able to load wordpress pages with no problem at all.   Are there any tips you can provide to get the posts to load properly?

**Comment by bentideswell** [comment]
Do you have any examples URL that I can take a look at?

**Comment by orbitrod** [comment]
It was working, but now nothing works.  I am working on double checking everything to see what happened.

But here are the links:
Wordpress home 
https://enoch.systems/en/ 

Wordpress page 
https://enoch.systems/en/sample-page/ 

Wordpress post 
https://enoch.systems/en/hello-world/

**Comment by orbitrod** [comment]
All seems to work now, flushing the cache seems to have done the trick.
