### ISSUE TITLE
Homepage vs Blog Listing Page

### ISSUE THREAD

**Issue by rain2o** [bentideswell/magento2-wordpress-integration#60]
This extension appears to treat the Blog Listing page as the Homepage, however that isn't always the case. In WordPress you can assign a page as the Front Page and a page as the Blog Listing Page. These can be the same, or two different pages. 

In most sites I work on, the Front Page is **not** the Blog Listing Page, and instead there is a separate page that serves that purpose. When applying this type of setup to my Magento/WordPress site with this extension, the Blog Listing Page is treated like the Homepage, and the Front Page is treated like a regular Post view. For the most part this doesn't result in too many actual issues, but does cause some developer confusion when building out layouts. I have noticed though that the page title and meta information gets pulled from the blog settings as opposed to the blog listing page in this situation, and the front page just pulls the title and meta information like a normal page. 

I don't have a clear resolution in mind, but it would be preferable if there were checks for these two options - Front Page and Blog Listing, and the layouts & blocks were implemented accordingly.

This is not an urgent issue and will probably require a decent amount of refactoring if implemented. I am open to further conversation around this issue and even helping with the implementation if interested.

Let me know your thoughts.

**Comment by bentideswell** [comment]
Yes this is a difficult issue and the wording of 'homepage' can be confusing. This was selected early in the module's history before the ability to change the WordPress homepage was added. In this context, homepage simply means the default posts page.

When you set a custom page to page to be the blog listing page, this then becomes the blog homepage. The page that displays the default blog posts, whether it is the standard homepage or a custom configured page, always has the handle 'wordpress_homepage_view'.

If you set a custom page to be the front page, this still retains it's default layout handles (wordpress_page_view, wordpress_page_view_ID etc).

I'm not entirely sure how to refactor things to work in a better way. The benefit to this method is that if you have your blog setup as default and at some future point add a custom homepage and cutom blog list page, the layout handles stay the same so your new blog list page doesn't suddenly break. It looks just how it did before setting the custom settings.

The only solution I can see is to set another layout handle (wordpress_front_page maybe?) to which ever page is the actual front page. On a default installation, this would be the blog listing page. If you set a custom page as your front page, this layout handle would transfer to this page instead.

Would this help?

**Comment by rain2o** [comment]
That makes sense. I can see where the confusing terminology would come in since that was established before WordPress made that change. I also just checked back with the WP template hierarchy and realized that the Blog Listing page defaults to `home.php` first, so that handle makes since with that in mind. It's been a while since I've been in WP theme development. 

I think your suggestions for implementing a `wordpress_front_page` handle would be a really nice feature to have. That would follow WP's template hierarchy as well for `front-page.php`. That sounds like a good solution for this, or at least a great starting point to see what else comes from it.

**Comment by bentideswell** [comment]
I have just released an update that contains this fix so I will close this issue. If you have any further comments or issues relating to this then please feel free to re-open this issue.
