### ISSUE TITLE
[M2.2] Error during setup:di:compile

### ISSUE THREAD

**Issue by Sam-PUMP** [bentideswell/magento2-wordpress-integration#63]
Getting an error during compile with Magento 2.2 - Is the module compatible? Do you know of a work-around for this error: 
## **[M2.2] Error during setup:di:compile**
`MiBPHP Fatal error:  Interface 'Magento\Sitemap\Model\ItemProvider\ItemProviderInterface' not found in`
[ /vendor/fishpig/module-wordpress/Model/Sitemap/ItemProvider/AbstractItemProvider.php](https://github.com/bentideswell/magento2-wordpress-integration/blob/35c4ceb1f1601edb4da40957faecfc1543930c44/Model/Sitemap/ItemProvider/AbstractItemProvider.php#L14) on line 14

### Thanks!!

**Comment by bentideswell** [comment]
Hi Sam, I have just released an update that fixes this problem.
