### ISSUE TITLE
PHP 7.1 Compatibility

### ISSUE THREAD

**Issue by adamj88** [bentideswell/magento2-wordpress-integration#64]
The composer.json puts a restriction on the versions of PHP allowed, it's not currently allowing PHP 7.1 which was introduced in Magento 2.2.

Would the below be able to be updated to include PHP 7.1 as well without any incompatibilities?

https://github.com/bentideswell/magento2-wordpress-integration/blob/master/composer.json#L7

**Comment by bentideswell** [comment]
I have just uploaded a new version that removes the PHP version restrictions.
