### ISSUE TITLE
if post have more (<!--more-->) tag it not get correct Excerpt content 

### ISSUE THREAD

**Issue by dipeshdmore** [bentideswell/magento2-wordpress-integration#71]
hello,
if a post have  tag expert function not show content before that tag .it show content with number of character default 50 .
file name :-   ..\Model\Post.php 
function name :-  _getPostTeaser function line number 178 
line of codes :- 
$content = strip_tags($this->getContent('excerpt'));

description :- 
by using strip_tag  it replace  "&lt; !--more--&gt;"  tag  in content and condition goes to false. 

Thanks .

**Comment by bentideswell** [comment]
I have just released an update that fixes this issue.
