### ISSUE TITLE
Composer Warning

### ISSUE THREAD

**Issue by maderlock** [bentideswell/magento2-wordpress-integration#72]
Whenever I do a composer install I see the following:

    Package bentideswel/magento2-wordpress-integration is abandoned, you should avoid using it. Use bentideswell/magento2-wordpress-integration instead.

This feels a little cyclical. This is what I have in composer.json:

    "require": {
        "magento/product-community-edition": "2.2.5",
        "bentideswel/magento2-wordpress-integration": "*"
     }

**Comment by bentideswell** [comment]
The composer.json file references bentideswel where as the correct name is bentideswell (two l's rather than one).
