### ISSUE TITLE
Blog pages not pulling in merged css

### ISSUE THREAD

**Issue by Kershrew** [bentideswell/magento2-wordpress-integration#73]
I have merged css enabled throughout the site but the blog pages are still searching for individual css files breaking the styles on the blog page.

**Comment by Kershrew** [comment]
Has this been resolved?

**Comment by bentideswell** [comment]
The latest version on my dev site doesn't have this issue. I will close the issue but if you can provide steps to recreate then I can re-open, debug and fix.
