### ISSUE TITLE
Regarding Shortcode plugin 500 error unable to view posts

### ISSUE THREAD

**Issue by Kershrew** [bentideswell/magento2-wordpress-integration#75]
Hi, I know this is for the main wordpress integration extension but I couldn't find a support area on the website other than to buy it and this is obviously a code error.

Since updating to Magento 2.2.5, switching to the new bentideswell repositories for the main wordpress integration and yoast and updating the shortcode plugin to the latest version I was unable to view individual posts on the website.

This is the error log:
```
[Thu Aug 23 19:01:48.111502 2018] [:error] [pid 1755651] [client 83.223.107.100:49763] PHP Fatal error:  Uncaught Error: Call to undefined function FishPig\\WordPress_PluginShortcodeWidget\\Model\\is_plugin_active() in /home/stahervi/public_html/app/code/FishPig/WordPress_PluginShortcodeWidget/Model/Shortcode.php:52, referer: http://hervia.mtcdevserver2.com/blog
[Thu Aug 23 19:01:48.111923 2018] [:error] [pid 1755651] [client 83.223.107.100:49763] #1 /home/stahervi/public_html/app/code/FishPig/WordPress_PluginShortcodeWidget/Helper/Core.php(1) : eval()'d code(330): call_user_func_array(Object(Closure), Array), referer: http://hervia.mtcdevserver2.com/blog
[Thu Aug 23 19:01:48.112081 2018] [:error] [pid 1755651] [client 83.223.107.100:49763] #2 /home/stahervi/public_html/app/code/FishPig/WordPress_PluginShortcodeWidget/Model/Shortcode.php(53): FishPig\\WordPress_PluginShortcodeWidget\\Helper\\Core->simulatedCallback(Object(Closure)), referer: http://hervia.mtcdevserver2.com/blog
[Thu Aug 23 19:01:48.112250 2018] [:error] [pid 1755651] [client 83.223.107.100:49763] #3 /home/stahervi/public_html/app/code/FishPig/WordPress_PluginShortcodeWidget/Model/Shortcode.php(34): FishPig\\WordPress_PluginShortcodeWidget\\Model\\Shortcode->processString('<h3>Retro Typog...'), referer: http://hervia.mtcdevserver2.com/blog
[Thu Aug 23 19:01:48.112435 2018] [:error] [pid 1755651] [client 83.223.107.100:49763] #4 /home/stahervi/public_html/vendor/bentideswell/magento2-wordpress-integration/Shortcode/AbstractShortcode in /home/stahervi/public_html/app/code/FishPig/WordPress_PluginShortcodeWidget/Model/Shortcode.php on line 52, referer: http://hervia.mtcdevserver2.com/blog
```

For now I have commented out line 52 of this file and the extension is running fine again but I cannot check any deeper because it is calling on a method declared in `\FishPig\WordPress_PluginShortcodeWidget\Model\Shortcode\AbstractShortcode` which has been masked with a file_put_contents so people don't steal your code.

**Comment by bentideswell** [comment]
Hi @Kershrew You can submit a support ticket for premium add-on modules using the Support section on each extension page:

https://fishpig.co.uk/magento/wordpress-integration/shortcodes-widgets/#support

That being said I have released an update that should fix this.

**Comment by Kershrew** [comment]
How did I miss that submit support ticket button, thanks!

**Comment by Kershrew** [comment]
Is there any way to require purchased extensions or do they always have to be downloaded?

**Comment by bentideswell** [comment]
It's not possible using composer but you could write a custom script that logs in to fishpig.co.uk, downloads the extensions, extracts them and then install them. This might even be something I try and do and release if there's any interest in it

**Comment by aholovan** [comment]
Seems there is a bug in FishPig\WordPress_PluginShortcodeWidget\App\View\AssetProvider
- Javascript is not working in FishPig/Wordpress blog when included in Magento block or widget..
It can be fixed in provideAssets method by adding 
_$htmlScraper = $this->htmlScraperFactory->create(['html' => $wpHtml]);
$wpHtml = $htmlScraper->getHtml() ?? $wpHtml;_
before 75:   _if ($assets = $this->getAssetsFromHtml($wpHtml, $magentoHtml)) {_
- to provide rendered html data added in block|widget to get all the assets

**Comment by bentideswell** [comment]
Hi @aholovan, are you able to provide steps to recreate the issue so that I can test the fix, please?

**Comment by aholovan** [comment]
> Hi @aholovan, are you able to provide steps to recreate the issue so that I can test the fix, please?

Hi Ben,
It's simple, just create a cms block in magento with some js inside. Then add it into wp post like
`{{widget type="Magento\Cms\Block\Widget\Block" template="widget/static_block/default.phtml" block_id="BLOCK_ID"}}`.
Verify post on magento frontend - it won't have the js snippet from cms block. Because when shortcode module is looking for js assest in post html there is not js yet but widget tag.

**Comment by aholovan** [comment]
Thanks @bentideswell ,
It works but seems it's better to avoid from unnecessary actions to figure out first is embedded Magento directives processing required, like 
```
if (strpos($wpHtml, '{{') !== false &&
     strpos($wpHtml, '}}') !== false &&
     preg_match_all('/\{\{(block|widget) [^}]*\}\}/', $wpHtml)
) {
     $wpHtmlScraper = $this->htmlScraperFactory->create(['html' => $wpHtml]);
     $wpHtml = $wpHtmlScraper->getHtml();
}
```
What do you mind?

**Comment by bentideswell** [comment]
The directive detection is built into the HTML scraper, so adding it here would be a duplication of code.

I agree it could be refactored and I have added this to my to do list, but for now I will keep it like this as it works and any added overhead from this is so small that it is not worth worrying about.

Thank you for the bug report and providing the fix, it makes my life easier!
