### ISSUE TITLE
Updated to 2.0.0.5 now viewing filter breaks page

### ISSUE THREAD

**Issue by Kershrew** [bentideswell/magento2-wordpress-integration#76]
When I click a category or archive I get this message:
```
Fatal error: Uncaught Error: Call to a member function applyPageConfigData() on boolean in /home/hervia/public_html/vendor/bentideswell/magento2-wordpress-integration/Block/Post/PostList/Wrapper/AbstractWrapper.php:25 Stack trace: #0 /home/hervia/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(272): FishPig\WordPress\Block\Post\PostList\Wrapper\AbstractWrapper->_prepareLayout() #1 /home/hervia/public_html/vendor/magento/framework/View/Layout/Generator/Block.php(150): Magento\Framework\View\Element\AbstractBlock->setLayout(Object(Magento\Framework\View\Layout\Interceptor)) #2 /home/hervia/public_html/vendor/magento/framework/View/Layout/GeneratorPool.php(80): Magento\Framework\View\Layout\Generator\Block->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context)) #3 /home/hervia/public_html/vendor/magento/framework/View/Layout.php(344): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Ob in /home/hervia/public_html/vendor/bentideswell/magento2-wordpress-integration/Block/Post/PostList/Wrapper/AbstractWrapper.php on line 25
```

Work around:
Only thing I've been able to do for this is hide the Category and Archive filters from the home of the blog page until the module is updated with a fix.

**Comment by bentideswell** [comment]
There are no filters on the homepage via the module. Do you have custom filters? If so, you may need to update your custom code to work with the new code base found in version 2.0.0.0 (and above). If you need any help with this then let me know.

**Comment by Kershrew** [comment]
Hi @bentideswell, I don't have anything custom in there, by filters I mean the links to the categories, archives and tags.

Although it does appear the changes in your 2.0.0.6 update has fixed it, might have been due to the tags not getting pulled through correctly which is what I think the issue was from looking at the commits.

Thanks for inadvertently fixing this :)
