### ISSUE TITLE
Updated to 2.0.0.5 now cannot pull blog posts in on multi-lingual site

### ISSUE THREAD

**Issue by Kershrew** [bentideswell/magento2-wordpress-integration#78]
My site's main language is /uk/ but also has a /us/ subdomain.
To make wordpress work with the /uk/ locale code I changed the base url to ***/uk/blog

This worked fine previously but now when I visit the us home page of my site (which has wordpress posts pulled onto it) I get this message:
```
1 exception(s):
Exception #0 (FishPig\WordPress\Model\Integration\IntegrationException): Your home URL (https://hervia.mtcserver.com/uk/blog) is invalid as it does not start with the Magento base URL (https://hervia.mtcserver.com/us).

Exception #0 (FishPig\WordPress\Model\Integration\IntegrationException): Your home URL (https://hervia.mtcserver.com/uk/blog) is invalid as it does not start with the Magento base URL (https://hervia.mtcserver.com/us).
#0 /home/hervia/public_html/vendor/bentideswell/magento2-wordpress-integration/Model/Integration/UrlTest.php(68): FishPig\WordPress\Model\Integration\IntegrationException::throwException('Your home URL (...')
#1 /home/hervia/public_html/vendor/bentideswell/magento2-wordpress-integration/Model/IntegrationManager.php(47): FishPig\WordPress\Model\Integration\UrlTest->runTest()
#2 /home/hervia/public_html/vendor/bentideswell/magento2-wordpress-integration/Helper/AssetInjector.php(75): FishPig\WordPress\Model\IntegrationManager->runTests()
#3 /home/hervia/public_html/vendor/bentideswell/magento2-wordpress-integration/Plugin/Magento/Framework/Controller/ResultPlugin.php(57): FishPig\WordPress\Helper\AssetInjector->process('<!doctype html>...')
#4 /home/hervia/public_html/vendor/magento/framework/Interception/Interceptor.php(146): FishPig\WordPress\Plugin\Magento\Framework\Controller\ResultPlugin->afterRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Magento\Framework\View\Result\Page\Interceptor), Object(Magento\Framework\App\Response\Http\Interceptor))
#5 /home/hervia/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#6 /home/hervia/public_html/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(26): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#7 /home/hervia/public_html/vendor/magento/framework/App/Http.php(139): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#8 /home/hervia/public_html/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#9 /home/hervia/public_html/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http\Interceptor->launch()
#10 /home/hervia/public_html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#11 {main}
```

Work around:
Comment out lines 66 - 69 of `\Model\Integration\UrlTest.php`:
```
if (strpos($homeUrl, $magentoUrl) !== 0) {
	// IntegrationException::throwException(
	// 	sprintf('Your home URL (%s) is invalid as it does not start with the Magento base URL (%s).', $homeUrl, $magentoUrl)
	// );
}
```

Resolution:
https://github.com/bentideswell/magento2-wordpress-integration/issues/78#issuecomment-419432966

Note:
Leaving this open to further discuss the multi-storecode support as mentioned in the comments.

**Comment by bentideswell** [comment]
If I understand correctly, you have a UK blog and on your US store, you don't have an integrated blog but you pull in the UK posts? If this is correct then you need to disable the Theme Integration option for the US store. This will stop the URL checks from occuring.

**Comment by Kershrew** [comment]
Hi @bentideswell, the store is the exact same on both languages, it has the same blog on both and pulls the posts into both so I need the integration there. I cannot have a /us/blog as wordpress only supports one domain name to run off of so for now the blog posts on the US site go to the UK blog.

I think this leads onto another issue that just putting /blog in the wordpress base url doesn't work with store codes in magento 2 as I have to set it as /uk/blog for it to show up on the uk site and then rewrite all the US blog links to the UK one.

**Comment by bentideswell** [comment]
Hi @Kershrew it's not possible to share one blog across different stores if those stores have URLs. WordPress needs a URL that it is configured to use (eg. /uk/blog/) so if you then try to load this on /us/blog/ the module won't let you. This stops duplicate content issues from having the same content on /us/blog/ and /uk/blog/.

To get around this, login to your Magento Admin and select WordPress from the nav menu and then select the US store. Once here, find the Theme Integration option and set this to No. 

Give this a try and let me know if it fixes the issue.

**Comment by Kershrew** [comment]
Hi @bentideswell, I did as you said and then removed my workaround and it doesn't error out anymore which is great I will bare that option in mind in the future.

To discuss futher about getting the one blog to with with multiple url's, is there no way of setting the url of the blog to say `/blog` and then when the page is being loaded from the magento side allow for the store code and pass the request to the blog still?
I'd like to be able to achieve having the blog on both url's if that is at all possible.

**Comment by bentideswell** [comment]
Yes, this feature is available for the M1 version of the module, but not yet available in M2. In M1 there is an Ignore Store Code option and when set, the module assumes that the Magento URL is the store's URL without the store code. This essentially allows all stores to share the 1 blog.

I am working on this feature now and will try and get it out in the next week. If you don't hear from me regarding this by Wednesday, feel free to post a quick reminder/comment in here.

**Comment by Kershrew** [comment]
Thanks @bentideswell you're a legend.

**Comment by bentideswell** [comment]
I've just released version 2.0.0.7 that I think should do this. There's a new config option in the Admin (Ignore Store Code) and when set to Yes, the store code is removed from the URL, making the blog available from /blog/ rather than /uk/blog/. This will allow you to share 1 blog with multiple stores without creating duplicate content issues.

**Comment by Kershrew** [comment]
I will test this now, what's the proper way to configure it then?

Wordpress url to have /blog with no store code?
Integrate with theme on all stores?
Have this enabled on all stores?

**Comment by bentideswell** [comment]
Do you have the FishPig theme installed and enabled in WordPress?

The correct way to set this up is to have your blog setup with a URL like /blog (no store code) and Integrate Theme set to Yes.

**Comment by Kershrew** [comment]
I do have the theme installed and enabled, it is pulled into my theme.

That's how I had it setup and it did not work as expected, visiting /UK/blog or /us/blog would cause the redirect I mentioned above to the image.

**Comment by Kershrew** [comment]
I think my wording must be unclear, I'm just using the WordPress theme as is, it integrates with my Magento thene straight out the box I haven't made any modifications to the code or anything.

The settings I tested with the 2.0.0.7 are in the comment I made above in bold and this still didn't work for me, I'm going to test it on a fresh build of Magento later on and see if the same thing happens.

**Comment by Kershrew** [comment]
Hi @bentideswell, It's been a while since we spoke about this issue but it is still relevant. If I upgrade the plugin to any version above 2.0.0.6 it breaks the blog and I am not able to access it on any url, I always get 301 redirected to an image in content/uploads.

Any ideas? I'd like to be able to use the multi-storecode side of the module but I just cannot go up past 2.0.0.6 without it being completely unusable.
