### ISSUE TITLE
Base table or view not found: "woptions"

### ISSUE THREAD

**Issue by thomas-harding** [bentideswell/magento2-wordpress-integration#79]
Version: 2.0.1.4
Magento Version 2.2.5 
WP Version 4.9.8

Error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magentosite.woptions' doesn't exist, query was: SELECT `woptions`.`option_value` FROM `woptions` WHERE (option_name = 'home')","1":"#0 

Steps to recreate:

- Install WordPress as per instructions
- Upload FishPig module as per instructions
- Go to "WordPress" in the sidebar
- I get the above error
- Reverting to FishPig 1.2.0.19 solved the issue for me

---

Very weird issue this. I can't find any record of "woptions" being a thing, not in the codebase nor the database itself. In the wp_config the prefix is listed as "wp_", so it seems like somethings stripping the "p_". 

I thought it could be related to the preg_match in /Model/WPConfig.php, so I forced it to use "wp_" as the prefix here, but alas, nothing.

**Comment by bentideswell** [comment]
Hi @thomas-harding,

This issue was fixed in the latest update, version 2.0.1.5. This was released a few minutes ago.

I will close this issue but if the upgrade doesn't resolve the issue then please re-open it.
