### ISSUE TITLE
Feeds not working as intended

### ISSUE THREAD

**Issue by Kershrew** [bentideswell/magento2-wordpress-integration#81]
Looks like if you go to the feeds for a tag or category it creates an exception in Magento and doesn't load the page.
E.g. https://www.hervia.com/uk/blog/tag/gifts-for-her/feed/

Could you take a look, thanks.

**Comment by bentideswell** [comment]
For full RSS feed support, you need to install the [Shortcodes & Widgets](https://fishpig.co.uk/magento/wordpress-integration/shortcodes-widgets/) add-on module.
