### ISSUE TITLE
Back button on multi-store config doesn't use url code

### ISSUE THREAD

**Issue by Kershrew** [bentideswell/magento2-wordpress-integration#82]
**Problem:**
When ignoring store code so we can have /us and /uk url's before the /blog segment all url's are changed correctly on all pages except for the back button on a post.

**Expected behaviour:**
When you are on a post on /uk/blog/my-test-post and click back it should take you back to *****.com/uk/blog.
When you are on a post on /us/blog/my-test-post and click back it should take you back to *****.com/us/blog.

**Actual behaviour:**
When you are on a post on /uk/blog/my-test-post and click back it takes you to *****.com/blog.
When you are on a post on /us/blog/my-test-post and click back it takes you to *****.com/blog.

**Comment by bentideswell** [comment]
Ignore Store Code removes the /uk/ and /us/ from the URL. If you have sub-directories in your Magento URLs or store codes, this feature allows you to have a single blog from the root of your domain. For example,

Store A: https://www.domain.com/en/
Store B: https://www.domain.com/es/
Store C: https://www.domain.com/de/

Usually blogs would have to have base URL in so blogs would be:

Blog A: https://www.domain.com/en/blog/
Blog B: https://www.domain.com/es/blog/
Blog C: https://www.domain.com/de/blog/

With Ignore Store Code enabled, you would have a single blog at:

https://www.domain.com/blog/

This would be available on all stores and the URL would be as above.

Based on your example, you seem to want the /uk/ and /us/ in your URLs should you should not enable the Ignore Store Code option. You want to use the store code.

**Comment by Kershrew** [comment]
I thought I needed the ignore store code option to enable it to apply any store code to the site, it works on every single url like it should except for the back button..

**Comment by bentideswell** [comment]
Ignore the Store code means when generating the base URL for the blog, ignore the store code. If your Magento store URL is https://www.domain.com/en/ then ignore the /en/ and just use https://www.domain.com/ as the base URL. As you want to keep the store code, you should set this option to No/False.

What do you mean by back button? Do you mean the back button in your browser?

**Comment by Kershrew** [comment]
I mean the back button on an individual post view. Every link on the blog goes to the correct store code except for this button.

**Comment by bentideswell** [comment]
The module doesn't provide a back button on posts so you must have added this yourself. Do you have an example link where I can see the issue?

**Comment by Kershrew** [comment]
For example:
https://www.hervia.com/uk/blog/yeezy-boost-350-v2-sesame/

So there isn't usually a link to go back to the blog list view?

**Comment by Kershrew** [comment]
Damn, just checked and we are adding that in manually, nevermind. My bad :)

**Comment by bentideswell** [comment]
No worries, glad it's resolved! I'll close this now but let me know if you have any other issues.

**Comment by Kershrew** [comment]
No worries, might be a good idea to add back button functionality in, even if it's just a method to pull the url in :)

**Comment by Kershrew** [comment]
Fair enough, was just a thought if it was an easy add to take you back to the previous page or listing for that individual view.

**Comment by bentideswell** [comment]
If you can send over more info on exactly how this should work, when I get an hour free I'd be happy to write some code for it for you. I might not add it to the core extension but you could add it to a small custom module and use it on your site. No worries if not but the offer is there.
