### ISSUE TITLE
how to apply magento 2 design theme to wp?

### ISSUE THREAD

**Issue by sunilit42** [bentideswell/magento2-wordpress-integration#9]
Hello,

is there any way to apply magento 2 theme to wp?

**Comment by bentideswell** [comment]
Yes, that's the point of the extension. Please follow the instructions in the Readme at https://github.com/bentideswell/magento2-wordpress-integration and you should be able to do this.

**Comment by abrorAbdullaev** [comment]
Why installation and integration guides are leading to 404 in Readme.md ?
