### ISSUE TITLE
wp-json Router Error

### ISSUE THREAD

**Issue by powelles** [bentideswell/magento2-wordpress-integration#91]
I get the following error when visiting `https://example.com/blog/wp-json`:

```
1 exception(s):
Exception #0 (LogicException): Front controller reached 100 router match iterations

Exception #0 (LogicException): Front controller reached 100 router match iterations
<pre>#1 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#2 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:94]
#3 Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#4 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:69]
#5 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#6 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#7 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#8 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:136]
#9 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#10 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:258]
#11 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:40]
</pre>
```

I've tried using stock installs with the following:

Magento Community 2.3.1 & Wordpress 5.2.1 & PHP 7.2
Magento Enterprise 2.3.0 & Wordpress 5.0 & PHP 7.2

Everything else works fine otherwise.

**Comment by bentideswell** [comment]
I will look into fixing the router loop but the wp-json API is no longer available through the integrated blog URL and should now be accessed using the WordPress installation (siteurl). This is generally the /wp URL

https://example.com/wp/wp-json

**Comment by powelles** [comment]
I can't seem to get `wp/wp-json` working with your plugin. I'm not sure if it's an Nginx config issue. I can get the route working before I enable the plugin and change the wordpress site url from `https://example.com/wp` to `https://example.com/blog`.

**Comment by bentideswell** [comment]
It may be an Nginx issue or it may be a WordPress config issue.

The latest versions of all FishPig modules use index.php in the URL so that rewrites aren't required for it to work.

http://example.com/wp/index.php?rest_route=/wp/v2/

Does this URL work for you?

The correct config for WordPress wp_options table should be:

siteurl = http://example.com/wp
home  = http://example.com/blog

Ensure that you have the FishPig theme installed and that it is at the latest version (3.0.0.7 at the time of writing). The latest version can be seen [here](https://github.com/bentideswell/magento2-wordpress-integration/blob/master/wptheme/style.css).

**Comment by powelles** [comment]
Thanks. It seems all I needed was to add the following to my nginx config: `rewrite ^(/blog/wp-json)(.*)$ /wp/index.php?rest_route=$2;`
