### ISSUE TITLE
Always redirected to WordPress home when trying to open Magento's home

### ISSUE THREAD

**Issue by ediseti** [bentideswell/magento2-wordpress-integration#94]
### Versions
- Magento CLI `2.3.2`
- FishPig_WordPress `2.0.8.23`
- FishPig_WordPress_Multisite `2.0.6.9`
- FishPig_WordPress_PluginShortcodeWidget `2.0.6.8`
- FishPig_WordPress_RelatedProducts `2.0.6.6`
- FishPig_WordPress_Root `2.0.6.4`

### Configs
**Magento**
- wordpress/setup/enabled `1`
- wordpress/multisite/enabled `0`
- wordpress/root/enabled `0`
- wordpress/multisite/smartswitching_enabled `0`
- wordpress/setup/path `wp`
- wordpress/setup/theme_integration `1`
- wordpress/setup/ignore_store_code `1`
- wordpress/xmlsitemap/enabled `1`

**WordPress**
- siteurl `https://example.com/wp`
- home `https://example.com/blog`
- template `fishpig`
- stylesheet `fishpig`
- current_theme `FishPig`

### Expected Result
- URL `https://example.com` should open Magento (CMS) homepage
- URL `https://example.com/blog` should open WordPress homepage

### Actual Result
- URL `https://example.com` redirects to `https://example.com/blog`

```
>>> https://example.com

> --------------------------------------------
> 302 Found
> --------------------------------------------

Status:	302 Found
Code:	302
Server:	nginx
Date:	Thu, 26 Sep 2019 20:28:52 GMT
Content-Type:	text/html; charset=UTF-8
Content-Length:	0
Connection:	close
Expires:	Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control:	no-store, no-cache, must-revalidate
Pragma:	no-cache
X-Redirect-By:	WordPress
Set-Cookie:	PHPSESSID=9307cbbbc198a082e5096ec890c94364; expires=Thu, 26-Sep-2019 21:28:42 GMT; Max-Age=3600; path=/; domain=example.com; HttpOnly
Access-Control-Allow-Origin:	https://*.example.com
Location:	https://example.com/blog
X-UA-Compatible:	IE=edge
```

**Comment by bentideswell** [comment]
Hi @ediseti, thank you for the detailed error report.

Your config all looks good but the following modules are out dated:

- FishPig_WordPress_Multisite 2.0.6.9 => 2.0.6.33
- FishPig_WordPress_PluginShortcodeWidget 2.0.6.8 => 2.0.6.32
- FishPig_WordPress_RelatedProducts 2.0.6.6 => 2.0.6.33
- FishPig_WordPress_Root 2.0.6.4 => 2.0.6.32

Please upgrade these modules and re-test. Can you also include the version of the FishPig theme in WordPress that is currently installed.

**Comment by ediseti** [comment]
Hi @bentideswell , thanks for the prompt response.
But wait, my add-on modules versions are all higher than your suggested versions. I also have tried to disable them one by one but the issue is still. So I'm suspecting it's the main module that has problem.
Tried to put some breakpoints on avaiable router and controller of `FishPig_WordPress` module as well. Nothing is called before the redirection.

Another thing, the `X-Redirect-By:	WordPress` response header looks odd, doesn't it?

As seen on `styles.css`, my FishPig theme is`Version: 3.0.0.4`.

**Comment by bentideswell** [comment]
Your versions are not higher than the suggested versions.  As an example, FishPig_WordPress_PluginShortcodeWidget, you have version 2.0.6.8 but the latest version is 2.0.6.32.

Please upgrade all FishPig modules to the latest version.

As for the FishPig theme, the latest version is 3.0.0.16:

https://github.com/bentideswell/magento2-wordpress-integration/blob/master/wptheme/style.css

If the theme is not auto updating then copy it manually from app/code/FishPig/WordPress/wptheme to wp-content/themes/fishpig

**Comment by ediseti** [comment]
Found that the redirect issue is caused by [qTranslate-XT WordPress Module](https://github.com/qtranslate/qtranslate-xt)
