### ISSUE TITLE
String: 'Search results for' is not being translated

### ISSUE THREAD

**Issue by kbakkes** [bentideswell/magento2-wordpress-integration#95]
In the getName() function in Model/Search there is a string that is currently not being translated on line 54. This could be resolved by putting `__()
` around the string.
	
```public function getName()
	{
		return 'Search results for ' . $this->getSearchTerm();
	}
```

**Comment by bentideswell** [comment]
I've released a fix for this using the following code:

    public function getName()
    {
      return __('Search results for %1', $this->getSearchTerm());
    }

This uses a variable for the search term and allows you to wrap the search term, if you wish.
