### ISSUE TITLE
Performance tweak - unnecessary factory causes object creation that isn't (potentially) required.

### ISSUE THREAD

**Issue by andy-igoo** [bentideswell/magento2-wordpress-integration#96]
Hi,

We've recently been running tests on a project of ours to try and iron out anything that slowing the site down and we may have found something that's of benefit to you (unless we're wrong). 

![Selection_999(211)](https://user-images.githubusercontent.com/37870907/70549362-f8edb500-1b6b-11ea-9aeb-ab0b64a45754.png)
This flame graph shows that on a checkout page request (and actually every request) there's a call to https://github.com/bentideswell/magento2-wordpress-integration/blob/master/Plugin/Magento/Framework/Controller/ResultPlugin.php 

Injecting `FishPig\WordPress\Helper\AssetInjectorFactory` to ensure a new object instead of `FishPig\WordPress\Helper\AssetInjector` directly is giving Magento 2 extra work to do. Looking at the class we can't see why we need a new object each time or why we need to ensure the object comes from Magento's object manager.

We're creating a patch for it to remove the factory and just use the original class. Is there any reason why there's a factory or was this just an oversight?

**Comment by bentideswell** [comment]
Hi Andy, thanks for the message. I've taken a look and yes, the AssetInjector is created on every request. This happens as it checks if WordPress has been integrated and if it has, it brings over the assets (js, css, fonts, etc) from WordPress and converts them to the correct format for Magento (RequireJS).

The way this works means that the object is only created once per request, so it's not as if the object is created multiple times. I don't see how changing this factory for the actual object would change anything as it would still mean the object would be created once per request, just as it is now.

A better optimisation might be to move the check for the ABSPATH constant from AssetInjector to the ResultPlugin.php file and if this isn't defined, don't create the AssetInjector object.

I've added the following static method to the AssetInjector:

	static public function isAbspathDefined()
	{
            return defined('ABSPATH');
	}

And then in ResultPlugin.php:

	public function afterRenderResult(ResultInterface $subject, ResultInterface $result, ResponseInterface $response = null)
	{
		if (!AssetInjector::isAbspathDefined()) {
			return $result;
		}

		// If Magento 2.1.9 or lower, $response won't be passed so load it separately
		if (!$response) {
			$response = $this->response;
		}

		$assetInjector = $this->assetInjectorFactory->create();

		if ($newBodyHtml = $assetInjector->process($response->getBody())) {
			$response->setBody($newBodyHtml);
		}
		
		return $result;
	}

This stops the object being created on pages where it's not needed (ie. checkout, account pages and any page where WordPress content isn't featured).

Hopefully this helps! Can you try updating and retesting?
