### ISSUE TITLE
Caption shortcode doesn't work

### ISSUE THREAD

**Issue by Krapulat** [bentideswell/magento2-wordpress-integration#98]
Hello,

I'm using latest Fishpig version 2.0.11.2 and Magento 2.3.4. And the [caption] is not working fine. It shows the shortcode code in frontend.

**Comment by bentideswell** [comment]
All shortcodes are supported via the [Shortcodes add-on module](https://fishpig.co.uk/magento/wordpress-integration/shortcodes-widgets/). Alternatively you can write your own small Magento module to parse and render the caption shortcode.
