### ISSUE TITLE
Warning: preg_match() issue 

### ISSUE THREAD

**Issue by atty31** [bentideswell/magento2-wordpress-integration#99]
Hi, when I access the blog url, I am receiving a report with:
`Exception #0 (Exception): Warning: preg_match(): Unknown modifier 'a' in /vendor/bentideswell/magento2-wordpress-integration/Controller/Router.php on line 157`.
This piece of code is causing the issue: `preg_match($route, $uri, $matches)`. 
In my case the `$route` value is `/^blog/artikel\/author\/([^\/]{1,})$/` and the `$uri` value is `overzicht`

I am running version: 2.0.11.11 of the module and my magento version is 2.3.5, also the same on 2.3.4 

Would you please have a look on this issue ? Let me know if you need more info. Thank you

**Comment by bentideswell** [comment]
Hi @atty31, a similar bug was fixed a few versions ago so please upgrade the module (and any other installed FishPig modules) to the latest version and test again.

If the error remains after upgrading, please provide the URLs you have configured in WordPress at Settings > General.

**Comment by atty31** [comment]
Hi @bentideswell, 
The issue is still present on version: 2.0.11.26 .  And yes, the url is an url rewrite(permanent) from Magento

**Comment by bentideswell** [comment]
When you go direct to the WordPress Admin, Magento code should not be loaded. This is a sign that you have configured something incorrectly.

What are the 2 WordPress URLs you have setup? You can find them in the wp_options DB table using the keys siteurl and home.

**Comment by atty31** [comment]
Hi @bentideswell  for both of them(site_url and home) are: {magento/base_url}/wordpress/

**Comment by bentideswell** [comment]
Do you mean siteurl and not site_url? This should be /wordpress but the home option should be something like /blog (the URL you want your blog to be visible on.

This all being said, requests directly to WordPress should not hit the Magento index.php file so your configuration must be wrong.

If you are using Nginx, ensure you have added configs for WordPress:

https://fishpig.co.uk/magento/wordpress-integration/nginx/
